Fix investment gallery styles
redneckz/wildless-cms-uni-blocks pull request #1005
Opened 2022-12-20 16:20 UTC by Irinaristova

Сссылка на баг - https://github.com/redneckz/temp_wcms/issues/750

2022-12-21 06:00 UTC, Mikage777 commented on src/components/InvestmentGallery/InvestmentGalleryContent.ts
> - */
Разве тут не нужна аннотация?

2022-12-21 07:52 UTC, Longraf approved these changes

2022-12-21 07:52 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +const cardComonProps = {
Тогда уж `cardCommonProps`

2022-12-23 08:32 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCardContent.ts
> +export type CardColumnsMode = '1' | '2';
может числами тогда?

2022-12-23 08:34 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +  const getCardsListLengthByIndicator = () =>
в данном случае можно без стрелки
```ts
const CARDS_COUNT_MAP = [4, 9];
...
const visibleCardsList = cardsList.slice(0, CARDS_COUNT_MAP[columnsMode - 1] || DEFAULT_CARDS_COUNT)`
```

columnsMode - может лучше числом?

2022-12-23 08:35 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +  return getCardsListLengthByIndicator().map((item, i) => (
visibleCardsList.map(...)

2022-12-23 10:24 UTC, redneckz commented on src/components/CarouselCard/CarouselCard.fixture.tsx
> +    <div className="container grid grid-cols-12">
верно ли это?
ведь карточки добавляются во flex контейнер.

2022-12-23 10:25 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +        p-9 w-[697px] min-h-[319px]
ещё и минимальная высота. по чему не по контенту то?

2022-12-23 10:25 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +    columnsMode === 2 ? cardsList.slice(0, 9) : cardsList.slice(0, 4);
магических констант много.
повтор slice
см. мой прошлый коммент

2022-12-23 10:25 UTC, redneckz commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +  const visibleCardsList = () =>
функция здесь не нужна

2022-12-23 10:26 UTC, redneckz commented on src/components/__snapshots__/Blocks.spec.tsx.snap
> +  <div
4 вложенных flex)
можно ли оптимизировать вёрстку?)

2022-12-23 10:27 UTC, redneckz approved these changes

2022-12-23 10:56 UTC, redneckz requested changes
Не по всем комментам договорились. В таких случаях resolve не ставится

2022-12-23 12:44 UTC, redneckz approved these changes

2022-12-23 13:16 UTC, merged