Refactor gallery and catalog block tranform into carouselCard
redneckz/wildless-cms-uni-blocks pull request #1078
Opened 2022-12-23 17:17 UTC by Longraf

Рефактор компонента Gallery в CarouselProductCard
Рефактор компонента Catalog в CarouselCatalogCard
Добавлена возможность добавлять 4 карточки в карусель

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1069

2022-12-26 06:24 UTC, vladeiko requested changes

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +      {description ? <div className="text-m-light text-left mb-4">{description}</div> : null}
Посмотри, пожалуйста, любой тикет на рефакторинг типографики. Там описано как всё это делать.
Я заводил тикет на каждый блок. А тут появляются новые блоки, на них тикеты не заведены, просто упустим.

Тут `Paragpraph`

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +          <div className="mr-1.5">Доступные цвета: </div>
Тут `Text`

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +      {price ? <div className="text-h3 text-left">{price}&nbsp;₽</div> : null}
Тут `Text`

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +              <span className={`text-m-light ${VersionAdditionalStyleMap[version]}`}>
Заменить на типографику. И не только эту строку, посмотри остальные тоже, пожалуйста

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +          {items?.length ? renderItems(items, isDotted, version) : null}
Все рендер-функции содержат тернарник внутри, а эта снаружи

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +        {button?.text ? renderButton({ button, buttonClassName: 'mt-6' }) : null}
Все рендер-функции содержат тернарник внутри, а эта снаружи.
Две функции отвсех отличаются. Малость странно

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  title ? <div className={HEADLINE_SMALL_VERSION[headlineSmallVersion]}>{title}</div> : null;
Используй типографику из ui-kit

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  description ? <div className={`text-l ${title ? 'mt-2' : ''}`}>{description}</div> : null;
Используй типографику из ui-kit

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  title ? <div className={HEADLINE_SMALL_VERSION[headlineSmallVersion]}>{title}</div> : null;
`Text`

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  description ? <div className={`text-l ${title ? 'mt-2' : ''}`}>{description}</div> : null;
Сюда можно `Paragraph`. Я по коду точно не могу сказать, надо на блок смотреть

2022-12-26 06:24 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +    <div className={`text-m-light mt-auto ${descriptionStyleMap[version ?? 'primary']}`}>
Тоже типографику использовать

2022-12-26 08:48 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +          {items?.length ? renderItems(items, isDotted, version) : null}
Done

2022-12-26 08:57 UTC, Longraf commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +      {price ? <div className="text-h3 text-left">{price}&nbsp;₽</div> : null}
Done

2022-12-26 08:57 UTC, Longraf commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +          <div className="mr-1.5">Доступные цвета: </div>
Done

2022-12-26 08:57 UTC, Longraf commented on src/components/CarouselCatalogCard/CarouselCatalogCard.tsx
> +      {description ? <div className="text-m-light text-left mb-4">{description}</div> : null}
Done

2022-12-26 08:57 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +        {button?.text ? renderButton({ button, buttonClassName: 'mt-6' }) : null}
Done

2022-12-26 09:14 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  description ? <div className={`text-l ${title ? 'mt-2' : ''}`}>{description}</div> : null;
Done

2022-12-26 09:14 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +    <div className={`text-m-light mt-auto ${descriptionStyleMap[version ?? 'primary']}`}>
Done

2022-12-26 09:36 UTC, Longraf commented on src/components/CarouselInvestmentCard/CarouselInvestmentCard.tsx
> +              <span className={`text-m-light ${VersionAdditionalStyleMap[version]}`}>
Done

2022-12-26 09:36 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  title ? <div className={HEADLINE_SMALL_VERSION[headlineSmallVersion]}>{title}</div> : null;
Done

2022-12-27 13:46 UTC, vladeiko approved these changes

2022-12-27 13:46 UTC, vladeiko commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  title ? <Paragraph size={HEADLINE_SMALL_VERSION[headlineSmallVersion]}>{title}</Paragraph> : null;
Тут скорее `Text`

2022-12-27 13:46 UTC, vladeiko commented on src/components/Gallery/GalleryCardInner.tsx
> +    <div className={`text-m-light mt-auto ${VersionAdditionalStyleMap[version ?? 'primary']}`}>
Тут типографику вставить

2022-12-27 14:28 UTC, Longraf commented on src/components/Gallery/GalleryCardInner.tsx
> +    <div className={`text-m-light mt-auto ${VersionAdditionalStyleMap[version ?? 'primary']}`}>
Этот компонент будет удаляться, нет смысла

2022-12-28 06:18 UTC, Longraf commented on src/components/CarouselProductCard/CarouselProductCard.tsx
> +  title ? <Paragraph size={HEADLINE_SMALL_VERSION[headlineSmallVersion]}>{title}</Paragraph> : null;
Done

2022-12-28 16:01 UTC, merged