Add ApplicationForm
redneckz/wildless-cms-uni-blocks pull request #1079
Opened 2022-12-25 14:35 UTC by KolyaBlacK

2022-12-26 06:28 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +    <span className="block text-m-light mb-[3px]">Сумма кредита, ₽</span>
Используй типографику из `ui-kit`, пожалуйста.
Подробное описание с примерами как понять `Text` или `Paragraph` в любом из тикетов "Рефакторинг типографики"

2022-12-26 06:28 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +    <span className="block text-m-light mb-[3px]">Сумма кредита, ₽</span>
Используй, пожалуйста, типографику из `ui-kit`

2022-12-26 06:28 UTC, vladeiko commented on src/components/ApplicationForm/Footnote.tsx
> +    <span className="text-secondary-text">Нажимая кнопку вы подтверждаете согласие с </span>
Используй, пожалуйста, типографику из `ui-kit`

2022-12-27 13:41 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +/* eslint-disable max-lines */
Игнор правила.
Много неиспользуемых значений в файле

2023-01-12 11:15 UTC, vladeiko requested changes

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +    <span className="block text-m-light mb-[3px]">Сумма кредита, ₽</span>
Используй ui-kit

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/Footnote.tsx
> +    <span className="text-secondary-text">Нажимая кнопку вы подтверждаете согласие с </span>
Используй ui-kit

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ResponseNotification.tsx
> +        <span className="text-secondary-text text-l-light">
Используй ui-kit

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/renderContacts.tsx
> +      <span>8 (800) 200-78-70</span>
Это ссылка с `href="tel:"`

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +/* eslint-disable max-lines */
Файл слишком большой. Уменьшить надо. Не надо отключать правило линтера

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +    <span className="block text-m-light mb-[3px]">Сумма кредита, ₽</span>
Либо это вообще `label`, возможно. Но хотя бы для начала на ui-kit заменить. Либо в `label` вложить ui-kit'овый текст

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +      <Heading headingType="h6" title="Вид эквайринга и регион" className="text-center mb-4" />
Не уверен, что это `Heading`. И ниже тоже. Мне кажется, что `label`. Но итоговую вёрстку не вижу. Трудно сказать на глаз. Но дико сомневаюсь, что это хэдинги

2023-01-12 11:15 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +      <Heading headingType="h6" title="Данные организации" className="text-center mb-4" />
Не уверен, что это Heading. И ниже тоже. Мне кажется, что label. Но итоговую вёрстку не вижу. Трудно сказать на глаз. Но дико сомневаюсь, что это хэдинги

2023-01-12 11:24 UTC, vladeiko requested changes

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationForm.tsx
> +
Очень сомнительный реестр компонентов

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +const acquiringTypes: Select[] = [
```suggestion
const ACQUIRING_TYPES: Select[] = [
```

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +  const [formState, setFormState] = useState<FormState>({
```suggestion
  const { button, link, handleForm } = props;
 
  const [formState, setFormState] = useState<FormState>({
```

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +type SelectsProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +type SlideCheckboxesProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormBusinessCard.tsx
> +type DataOrganizationProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormBusinessCard.tsx
> +type RegionProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormBusinessCard.tsx
> +type DataOrganizationProps = {
RenderData....Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormBusinessCard.tsx
> +type RegionProps = {
Render....Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +type CreditParametersProps = {
Render...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +type CreditParametersProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +type DataOrganizationProps = {
Render...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +type DataOrganizationProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +type BankOfficesProps = {
interface
Redner...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +export interface InputRangeProps {
Redner...Props
По идее можно унаследовать от InputRangeProps

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormCredit.tsx
> +    <span className="block text-m-light mb-[3px]">{props.label}</span>
Типографика

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormDeposit.tsx
> +type DataOrganizationProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormDeposit.tsx
> +type DataOrganizationProps = {
Render...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormWed.tsx
> +type DataOrganizationProps = {
interface
Render...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/Footnote.tsx
> +type FootnoteProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ResponseNotification.tsx
> +type ResponseNotificationProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/renderQuestionsInterested.tsx
> +type QuestionsInterestedProps = {
interface

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/renderQuestionsInterested.tsx
> +type QuestionsInterestedProps = {
Render...Props

2023-01-12 11:24 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationForm.tsx
> +  const handleForm = useCallback(() => {
handleSubmit?

2023-01-12 11:27 UTC, vladeiko requested changes

2023-01-12 11:27 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormWed.tsx
> +export type HandleChangeState = (state: Partial<FormState>) => void;
HandleFormStateChange
HandleFormDataChange

2023-01-12 11:27 UTC, vladeiko commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +export interface FormState {
Во всех формах у этой сущности одно имя

2023-01-12 11:33 UTC, vladeiko commented
В целом большинство комментариев однотипны. Так что где-то мог что-то пропустить. Проверь, пожалуйста, дополнительно сам

2023-01-12 12:59 UTC, vladeiko approved these changes

2023-01-13 06:09 UTC, redneckz commented on src/components/ApplicationForm/ApplicationFormWed.tsx
> +    [setFormState],
сеттеры в deps не включаются

2023-01-13 06:10 UTC, redneckz commented on src/components/ApplicationForm/ApplicationFormWed.tsx
> +  const handleChange: HandleFormStateChange<WedFormState> = useCallback(
выглядит как generic hook для форм
```ts
const handleChange: HandleFormStateChange<WedFormState> = useCallback(...)
const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {...
```

2023-01-13 06:12 UTC, redneckz commented on src/components/ApplicationForm/Footnote.tsx
> +      <Button href={link.href} target={link.target} className="text-primary-main">
дважды text-primary-main"?
здесь

2023-01-13 06:12 UTC, redneckz commented on src/components/ApplicationForm/Footnote.tsx
> +        <Text color="text-primary-main">{link.text}</Text>
и здесь?

2023-01-13 06:15 UTC, redneckz commented on src/components/ApplicationForm/Footnote.tsx
> +      <Button href={link.href} target={link.target} className="text-primary-main">
есть три версии кнопки с таким цветом текста
![image](https://user-images.githubusercontent.com/5698620/212250455-2203be36-6cd8-4f82-b46e-1e25e59b9a49.png)
есть ли срдеи них подходящая версия?

2023-01-13 06:17 UTC, redneckz commented on src/components/ApplicationForm/WrapperSelect.tsx
> +  ({ data, fieldLabel, fieldValue, selected, placeholder = '', setSelected, label }) => {
много мест с сеттерами в пропах компонент (setSelected)
обычный контракт для таких контролов
`value: T` и `onChange(newValue: T)`

2023-01-13 06:17 UTC, redneckz commented on src/components/ApplicationForm/renderBankOffices.tsx
> +        data={regions}
options имеется в виду?

2023-01-13 06:21 UTC, redneckz commented on src/components/ApplicationForm/renderSubmitButton.tsx
> +  const buttonStyle = getRegularButtonClasses({
жаль, что так приходится делать.
в идеале, здесь должен подходить Button компонент с `type="submit"` в пропах

2023-01-13 06:51 UTC, KolyaBlacK commented on src/components/ApplicationForm/renderBankOffices.tsx
> +        data={regions}
> `options={regions}` имеется в виду?

поменять имя пропса на options?

2023-01-13 06:53 UTC, redneckz commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +  }, [ACQUIRING_TYPES]);
константы в зависимостях не нужны

2023-01-13 06:54 UTC, redneckz commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +    setFormState((oldState) => ({
обычно, useEffect с вызовом сеттера внутри - это антипаттерн

2023-01-13 06:55 UTC, redneckz commented on src/components/ApplicationForm/ApplicationFormAcquiring.tsx
> +  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
useCallback неплохо бы

2023-01-13 07:56 UTC, Mikage777 approved these changes

2023-01-13 08:13 UTC, redneckz approved these changes

2023-01-13 09:01 UTC, merged