Refactor recommendations block
redneckz/wildless-cms-uni-blocks pull request #1082
Opened 2022-12-26 13:54 UTC by Irinaristova

Рефакторинг и доработка блока рекомендаций  - https://github.com/redneckz/wildless-cms-uni-blocks/issues/800

2022-12-26 14:00 UTC, vladeiko approved these changes

2022-12-26 14:00 UTC, vladeiko commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +        className={`relative text-left text-left border border-solid box-border p-7 min-w-[524px]
Точно ли надо задавать `min-w` тут? Оправданно ли?

2022-12-29 10:09 UTC, Longraf requested changes

2022-12-29 10:09 UTC, Longraf commented on src/components/__snapshots__/Blocks.spec.tsx.snap
> -
Компонент удаляется только после написания миграции.

2022-12-29 10:12 UTC, Longraf requested changes

2022-12-29 10:12 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +        className={`relative text-left text-left border border-solid box-border p-7 min-w-[524px]
`text-left `атом встречается 2 раза подряд

2022-12-29 13:45 UTC, Longraf approved these changes

2022-12-29 14:13 UTC, Longraf commented
Сборка упала, нужно добавить компонент в Block.ts

2022-12-29 15:06 UTC, merged