Добавлен новый блок "Фильтрация"
redneckz/wildless-cms-uni-blocks pull request #1083
Opened 2022-12-27 03:15 UTC by end0rfin

Задача:
[Uni Blocks] Новый блок для фильтрации блоков по выбранным параметрам #960
https://github.com/redneckz/wildless-cms-uni-blocks/issues/960

Реализована вёрстка и функционал основных элементов.

Функционал работы самих фильтров и фильтрации не реализован.

2022-12-27 13:37 UTC, vladeiko requested changes

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/FiltrationBlock.tsx
> +export const FiltrationBlock: JSXBlock<FiltrationBlockProps> = JSX<FiltrationBlockProps>(
```suggestion
};

export const FiltrationBlock: JSXBlock<FiltrationBlockProps> = JSX<FiltrationBlockProps>(
```

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/FiltrationBlock.tsx
> +  setMonthsValue?: (value: number) => void;
Сеттеры передаются в функцию

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/FiltrationBlock.tsx
> +const renderAmountGap = ({ amount, gap, setMoneyValue, setMonthsValue }: renderAmountGapProps) => (
Сеттеры передаются в функцию

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/computeValue.ts
> +export const computeValue = (
Наверное лучше назвать `get`

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/getMappedValuesGroups.ts
> +      groups[groupIndex]['groupValues'] = [];
Сайд эффект

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/getMappedValuesGroups.ts
> +        result[groupIndex] = `#${itemIndex}`;
Сайд эффект

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +  toggleGroupValue: (valueIndex: number, groupIndex: number) => void;
Свойство должно именоваться с `on`

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +        onClick={() => toggleGroupValue(valueIndex, groupIndex)}
Свойство должно именоваться с `on`. А вот то, что принимает `onClick` должно именоваться как `handle`. То есть, если бы этот обработчик был бы объявлен в теле компонента, он бы начинался с `handle`

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +        <div>{value.text}</div>
Типографика

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +import { GroupValues } from './FiltrationBlockContent';
type

2022-12-27 13:37 UTC, vladeiko commented on src/components/FiltrationBlock/renderValuesGroups.tsx
> +        <div className="text-m-light text-secondary-text mb-4">{group.text}</div>
Типографика

2022-12-28 08:07 UTC, end0rfin commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +  toggleGroupValue: (valueIndex: number, groupIndex: number) => void;
Внёс исправления.

2022-12-28 08:57 UTC, end0rfin commented on src/components/FiltrationBlock/renderGroupValues.tsx
> +        onClick={() => toggleGroupValue(valueIndex, groupIndex)}
Внёс исправления.

2022-12-29 13:39 UTC, end0rfin commented on src/components/FiltrationBlock/FiltrationBlock.tsx
> +  setMonthsValue?: (value: number) => void;
Внёс исправления в код

2022-12-29 13:39 UTC, end0rfin commented on src/components/FiltrationBlock/FiltrationBlock.tsx
> +const renderAmountGap = ({ amount, gap, setMoneyValue, setMonthsValue }: renderAmountGapProps) => (
Внёс исправления в код

2022-12-29 20:56 UTC, end0rfin commented on src/components/FiltrationBlock/getMappedValuesGroups.ts
> +      groups[groupIndex]['groupValues'] = [];
Переработал функцию.

2022-12-29 20:56 UTC, end0rfin commented on src/components/FiltrationBlock/getMappedValuesGroups.ts
> +        result[groupIndex] = `#${itemIndex}`;
Переработал функцию

2023-01-16 07:25 UTC, vladeiko requested changes

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +    const handleToggleGroupValue = useMemo(
Тут явно нужен `useCallback`

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +        mappedValue[groupIndex] = getValue(value, valueIndex as number, groupType);
Почему `valueIndex as number`? В `onClickProps` какой у него тип? Если `string`, а `getValue` требует `number`, то надо выполнять явное приведение типов `Number(valueIndex)`. И как-то странно, что index не являеется number сам по себе

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +        mappedValue[groupIndex] = getValue(value, valueIndex as number, groupType);
Если в `getValue` есть какая-либо математика, то работать корректно не будет. JS по-особому обрабатывает числа

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +type renderAmountGapProps = {
```suggestion
type RenderAmountGapProps = {
```

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +  updateMonthsValue,
Думаю, что эти `update` должны называться всё-таки `onMoneyChange`  и `onMonthsChange`

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +const renderAmountGap = ({
```suggestion
};

const renderAmountGap = ({
```

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +  buttonConfirm: ButtonConfirm | undefined,
```suggestion
  confirmButton: ButtonConfirm | undefined,
```

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +  buttonCancel: ButtonCancel | undefined,
```suggestion
  cancelButton: ButtonCancel | undefined,
```

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +  handleClickButtonCancel: () => void,
И тогда получается:
```suggestion
  handleCancelButtonClick: () => void,
```

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +  handleClickButtonCancel: () => void,
Типы тогда тоже переименовать можно

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/getMappedValuesGroups.ts
> +};
Можно или к тернарнику свести или `(groups || []).reduce`

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/getMappedValuesGroups.ts
> +};
Лучше задать значение по умолчанию для `groups`

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/Filtration.tsx
> +type renderAmountGapProps = {
interface

2023-01-16 07:25 UTC, vladeiko commented on src/components/Filtration/renderGroupValues.tsx
> +type RenderGroupValuesProps = {
interface

2023-01-16 07:25 UTC, vladeiko commented on src/ui-kit/SlideCheckbox/SlideCheckbox.tsx
> +  onClick?: (checked: boolean, props?: any) => void;
Странный контракт с `props: any`

2023-01-16 07:25 UTC, vladeiko commented on src/ui-kit/SlideCheckbox/SlideCheckbox.tsx
> +  props?: any;
Странные `props: any`

2023-02-02 09:19 UTC, Mikage777 commented
Блок фильтрации был влит в МР https://github.com/redneckz/wildless-cms-uni-blocks/pull/1257

2023-02-02 09:19 UTC, closed without merging