Add Location modal
redneckz/wildless-cms-uni-blocks pull request #1087
Opened 2022-12-27 11:27 UTC by andreySimonenko

https://github.com/redneckz/wildless-cms-uni-blocks/issues/756

2022-12-27 13:29 UTC, redneckz commented on src/hooks/useLocation.ts
> +  const { data } = useAsyncData<RegionData>(REGION_URL, fetchJSONUnsafe);
`const { data } = useCachedAsyncData<RegionData>(REGION_URL, fetchJSONUnsafe);`

внутри useAsyncData и оборачивание переданного fetchчтото через useCallback с целью кэширования в storage

2022-12-27 13:31 UTC, vladeiko requested changes

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +      <a className="cursor-pointer text-green" role="link" onClick={close}>
Используется тег `<a/>` и ставится `role="link"`. Для данного тега нет необходимости задавать роль.
Кроме того судя по тому как используется - это не линка, а кнопка. Нельзя использовать данный тег. Вроде у нас под кнопки есть компонент

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +      Сейчас выбран:&nbsp;
Используй типографику из `ui-kit`

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +      Сейчас выбран:&nbsp;
Можно посмотреть любой тикет на рефакторинг типографики

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +        <div className="text-h6 mb-2.5">{letter}</div>
Типографика

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +          onClick={() => {
Это скорее кнопка, чем ссылка

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +      <div className="text-m-light text-secondary-text mb-4">Представительства за рубежом:</div>
Типографика

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +    <a className="hover:text-primary-hover" href={office.href} target={office.target}>
Вот это ссылка. И тут по идее должен использоваться `useLink`

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/useGetRegions.ts
> +export function useGetRegions(): [SystemRegion[], Map<string, SystemRegion[]>] {
Судя по имени функции она должна вернуть getter-функцию регионов.
Судя по коду должна называться `useRegions`

2022-12-27 13:31 UTC, vladeiko commented on src/utils/groupBy.ts
> +export const groupBy = <K, V>(list: Array<V>, keyGetter: (input: V) => K): Map<K, Array<V>> => {
Лучше будет каррировать функцию

2022-12-27 13:31 UTC, vladeiko commented on src/ui-kit/Location/Location.tsx
> +
```suggestion
```

2022-12-27 13:31 UTC, vladeiko commented on src/components/Header/HeaderBurger.tsx
> +        <button className="flex items-center text-s text-secondary-text p-0 mb-4 bg-transparent cursor-pointer">
Типографика

2022-12-27 13:31 UTC, vladeiko commented on src/components/Header/HeaderBurger.tsx
> +        <button className="flex items-center text-s text-secondary-text p-0 mb-4 bg-transparent cursor-pointer">
Нет `onClick`. Это точно кнопка?

2022-12-27 13:31 UTC, vladeiko commented on src/components/Header/HeaderBurger.tsx
> +        <button className="flex items-center text-s text-secondary-text p-0 mb-4 bg-transparent cursor-pointer">
Для кнопок вроде был компонент

2022-12-27 13:32 UTC, Mikage777 commented on src/hooks/useLocation.ts
> +  const [location, setLocation] = useState<RegionData>({ name: defaultLocation });
```suggestion
  const [location, setLocation] = useState<RegionData>(currentLocation ?? { name: defaultLocation });
```

Думаю тут стоит запихать значение, которое мы определяли ранее. 

При первом заходе на сайт пользователь увидит `defaultLocation` из справочника, лишь на секунду, затем подтянется результат из эндпоинта. 
При следующем заходе на сайт, значение, что мы сохраняли ранее в localStorage будет сразу отображено пользователю. И он не увидит "подмены" после ответа эндпоинта

2022-12-27 13:35 UTC, redneckz commented on src/hooks/useLocation.ts
> +  const { data } = useAsyncData<RegionData>(REGION_URL, fetchJSONUnsafe);
```ts
storage.set(`async:${key}`, { timestamp: Date.now(), response })
```

2022-12-27 13:36 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +  baseRegionName: string;
всегда вопросики на полях

2022-12-27 13:38 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +  const stopWordsPattern = new RegExp(stopwords.join('|'), 'gi');
лучше в функцию clenupЧтото

2022-12-27 13:39 UTC, Mikage777 commented on src/hooks/useLocation.ts
> +      currentLocation && currentLocation.manual
```suggestion
      currentLocation?.region && currentLocation?.manual
```

Возможно что стоит добавить проверку и на наличие `region`, чтобы уж наверняка

2022-12-27 13:41 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +        .sort((a, b) => a.baseRegionName.localeCompare(b.baseRegionName))
похоже на уровень представления

2022-12-27 13:42 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +            letter: baseRegionName.charAt(0),
можно убрать. так как всегда вычисляется из `baseRegionName`

2022-12-27 13:44 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +            letter: baseRegionName.charAt(0),
```ts
export const чтото = (region) => region.baseRegionName.charAt(0);
```

2022-12-27 13:44 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +  return [regions, groupBy(regions, (region) => region.letter)];
все преобразования уровня предсатвления

2022-12-27 13:47 UTC, redneckz commented on src/ui-kit/Location/useGetRegions.ts
> +export interface SystemRegion extends Region {
эта структура пропадёт при переносе на уровень представления

2022-12-27 13:48 UTC, redneckz commented on src/model/Region.ts
> +export interface Region {
лучше прямо в хук положить useGetRegions

2022-12-27 13:52 UTC, redneckz commented on src/utils/groupBy.ts
> +      map.set(key, [item]);
`map.set(key, [item].concat(collection));`

2022-12-27 13:54 UTC, redneckz approved these changes

2022-12-29 10:21 UTC, Longraf commented on src/ui-kit/Location/Location.fixture.tsx
> +import { Region } from '../../model/Region';
type

2022-12-29 10:21 UTC, Longraf commented on src/ui-kit/Location/Location.tsx
> +    <div className="border border-main-divider border-b-0 border-x-0 mt-7 pt-7">
`border border-b-0 border-x-0` может лучше не обнулять 3 бордера, а просто сделать `border-t-1` (не уверен в правильности написания атома)

2022-12-29 10:21 UTC, Longraf commented on src/ui-kit/Location/SearchBar.tsx
> +              outline-none pr-[6%] border-main-stroke hover:border-primary-hover active:border-primary-text focus:border-primary-text`}
pr-[6%] странный атом, он точно нужен именно такой, а не фиксированное значение?

2022-12-29 14:02 UTC, andreySimonenko commented on src/components/Header/HeaderBurger.tsx
> +        <button className="flex items-center text-s text-secondary-text p-0 mb-4 bg-transparent cursor-pointer">
`onClick` - убрал временно, так как пока нет макета для мобильной версии

2022-12-29 14:02 UTC, andreySimonenko commented on src/model/Region.ts
> +export interface Region {
вынес

2022-12-29 14:04 UTC, andreySimonenko commented on src/ui-kit/Location/Location.tsx
> +    <div className="border border-main-divider border-b-0 border-x-0 mt-7 pt-7">
border - без этого стиля не работает, а он везде добавляет border

2022-12-29 14:04 UTC, andreySimonenko commented on src/ui-kit/Location/SearchBar.tsx
> +              outline-none pr-[6%] border-main-stroke hover:border-primary-hover active:border-primary-text focus:border-primary-text`}
убрал

2022-12-29 14:06 UTC, andreySimonenko commented on src/utils/groupBy.ts
> +export const groupBy = <K, V>(list: Array<V>, keyGetter: (input: V) => K): Map<K, Array<V>> => {
с какой целью? тут всего два параметра

2022-12-29 14:07 UTC, andreySimonenko commented on src/utils/groupBy.ts
> +export const groupBy = <K, V>(list: Array<V>, keyGetter: (input: V) => K): Map<K, Array<V>> => {
плюс во всех библиотеках для этого метода используется подобная сигнатура. зачем отходить от общих стандартов.

2022-12-29 14:42 UTC, andreySimonenko commented on src/ui-kit/Location/Location.tsx
> +    <div className="border border-main-divider border-b-0 border-x-0 mt-7 pt-7">
заменил на `border-t`

2022-12-29 14:50 UTC, Mikage777 approved these changes

2022-12-29 14:55 UTC, vladeiko approved these changes

2022-12-29 14:59 UTC, merged