Feature/header right block
redneckz/wildless-cms-uni-blocks pull request #12
Opened 2022-05-20 14:15 UTC by andreySimonenko

2022-05-24 09:10 UTC, michaelkutuzov requested changes

2022-05-24 09:10 UTC, michaelkutuzov commented on src/HeaderRightBlock.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Общие соображения:
1. Нейминг, HeaderRightBlock как-то уж общо совсем звучит. Предлагаю то, что содержит ссылки на страницы, называть HeaderPrimaryMenu, а этот компонент — HeaderSecondaryMenu. Так будет лучше, потому что он и справа быть не обязан, вообще позицию или цвет фиксировать в названии не оч круто.
3. Предлагаю все части шапки сложить в один каталог и экспортировать только саму шапку, а все эти подменю оставить приватными.

2022-05-24 14:08 UTC, andreySimonenko commented on src/HeaderRightBlock.tsx
> +        Москва
Добавил props location

2022-05-24 14:08 UTC, andreySimonenko commented on src/HeaderRightBlock.tsx
> +        className={`mr-5 font-sans text-pimary text-sm hover:text-brand no-underline`}
исправил

2022-05-24 14:10 UTC, andreySimonenko commented on src/HeaderRightBlock.tsx
> +      <button
Сделал функцию для первых двух кнопок. Кнопку с иконкой грида оставил в отдельной функции. Ховур добавил.

2022-05-24 14:10 UTC, andreySimonenko commented on src/HeaderRightBlock.tsx
> +import { JSX } from '@redneckz/uni-jsx';
1. Переименовал
2. Вынес

2022-05-25 09:07 UTC, michaelkutuzov approved these changes

2022-05-25 09:21 UTC, merged