Added validation
redneckz/wildless-cms-uni-blocks pull request #1248
Opened 2023-01-26 14:47 UTC by KolyaBlacK

2023-01-26 15:51 UTC, Mikage777 commented
![image](https://user-images.githubusercontent.com/5903264/214882805-4cffdc9c-3f94-40fa-aaea-ea725e652e1e.png)
пайплайн ушел в бесконечный цикл.

2023-02-02 08:02 UTC, vladeiko requested changes

2023-02-02 08:02 UTC, vladeiko commented on src/components/ApplicationForm/validate.ts
> +//TODO можно добавить свитч кейс для разных правил валидации (имейл и тд)
TODO комментарии корректно пишутся так:
```suggestion
// TODO: Можно добавить свитч кейс для разных правил валидации (имейл и тд)
```

2023-02-02 08:02 UTC, vladeiko commented on src/components/ApplicationForm/validate.ts
> +    case 'inn':
идентификационный номер налогоплательщика = taxpayer identification number (ИНН = TIN).

Установи следующие `extensions`:
    "streetsidesoftware.code-spell-checker",
    "streetsidesoftware.code-spell-checker-russian"

В папке с проектом лежит .vscode папка, в ней в рекомендациях прописаны спеллчекеры

2023-02-06 06:22 UTC, vladeiko approved these changes

2023-02-06 06:22 UTC, vladeiko commented on src/components/ApplicationForm/InputControl.tsx
> +        <div className="h-2">
Подскажи, пожалуйста, а это зачем?

2023-02-06 06:22 UTC, vladeiko commented on src/components/ApplicationForm/SelectControl.tsx
> +        <div className="h-2">
Подскажи, пожалуйста, а это зачем?

2023-02-06 06:22 UTC, vladeiko commented on src/components/ApplicationForm/validate.ts
> +    case 'inn':
По этой ветке не получил никакой ответ

2023-02-06 06:23 UTC, vladeiko commented on src/components/ApplicationForm/validate.ts
> +    case 'inn':
По этой ветке не получил ответ

2023-02-06 09:46 UTC, merged