Fix stepsblock
redneckz/wildless-cms-uni-blocks pull request #1268
Opened 2023-01-30 17:39 UTC by Irinaristova

https://github.com/redneckz/temp_wcms/issues/859

2023-01-30 18:11 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlockContent.ts
> +    buttons?: ButtonWithIconProps[];
А это точно корректно, что у блока может быть до 2-ух кнопок включительно, помимо тех которые внутри шагов?

Тогда ещё нужна миграция, чтобы контент текущего пропа `button` попал в массив `buttons`

2023-01-30 18:11 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlock.tsx
> +                renderStep({ styleMap, isMainButton: Boolean(buttons?.[0]?.text), version }),
Может быть 2 кнопки, проверяется только наличие текста в первой кнопке блока.
Тогда или проверять текст в каждой,  `isMainButton: Boolean(buttons?.every(b => b?.text))` или проверять по наличию кнопок у основного блока  `isMainButton: Boolean(buttons?.length)`

2023-01-30 18:11 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlock.tsx
> +        {renderButtonsSection(buttons, { className: 'flex justify-center mt-8 min-w-60' })}
Не уверен, что так будет корректно. Пока снепштоты ещё обновляются. Но скорее всего будет проблема с размером кнопок внутри секции, если их больше одной

2023-01-30 18:11 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlock.ui.json
> +          }
Если `buttons` добавляется на замену `button` - то button можно убрать отсюда

2023-01-30 18:18 UTC, Longraf requested changes

2023-01-30 18:18 UTC, Longraf commented on src/components/StepsBlock/StepsBlock.tsx
> +      stepVersion === 'secondary' ? 'group-data-primary:text-white' : 'text-secondary-text';
Тут не требуется условие, можно просто строку с атомами `text-secondary-text group-data-primary:text-white`

2023-01-30 18:18 UTC, Longraf commented on src/components/StepsBlock/StepsBlock.tsx
> -          <span className={`text-h4 group-data-transparent:${styleMap.iconText} text-primary-text`}>
Тут тоже ранее было правильно, если же хотела избавиться от переменной `${}`то нужно замени переменную на конкретный атом

2023-01-30 18:18 UTC, Longraf commented on src/components/StepsBlock/StepsBlockContent.ts
> +    buttons?: ButtonWithIconProps[];
Да в случае изменения контракта нужна миграция

2023-01-30 18:26 UTC, Irinaristova commented on src/components/StepsBlock/StepsBlockContent.ts
> +    buttons?: ButtonWithIconProps[];
да, в блоке может быть до 2 кнопок не больше

2023-01-30 18:27 UTC, Irinaristova commented on src/components/StepsBlock/StepsBlock.tsx
> +                renderStep({ styleMap, isMainButton: Boolean(buttons?.[0]?.text), version }),
надо в каждой кнопке проверять наличие текста

2023-01-30 18:28 UTC, Irinaristova commented on src/components/StepsBlock/StepsBlock.ui.json
> +          }
там есть условие либо кнопка в каждом блоке шага, либо до 2 кнопок в основном блоке

2023-01-30 19:26 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlock.ui.json
> +          }
Да, я не заметил, вложенность `button` внутрь `steps`... Но тогда тут другой момент, `buttons` надо поднять из `content.steps.items` выше, на один уровень с шагами внутрь `content`.
`content.steps.items.button` - для кнопки внутри шага
`content.buttons.items` - для кнопок блока

2023-01-31 09:31 UTC, Longraf approved these changes

2023-01-31 10:25 UTC, Grimitsu commented on src/components/StepsBlock/StepsBlock.tsx
> +                renderStep({ styleMap, isMainButton: Boolean(buttons?.[0]?.text), version }),
👍 , тогда первый вариант, но лучше вычисление флага вынести константой выше, чтобы не было постоянного пересчёта в `steps.map`

```ts
const isMainButton = Boolean(buttons?.every(b => b?.text))
// и передать в renderStep
 renderStep({ styleMap, isMainButton, version })
```

2023-02-07 09:06 UTC, merged