Migration for Recommendation.tsx and delete Recommendation
redneckz/wildless-cms-uni-blocks pull request #1274
Opened 2023-01-31 16:43 UTC by Longraf

Написана миграция для Recommendation
Удалён Recommendation
Необхоидимо ещё проверить правки
https://github.com/redneckz/wildless-cms-uni-blocks/issues/1069

2023-01-31 16:52 UTC, Mikage777 commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> -  <div className={style('flex', setAdditionalIconStyles(items))}>
на 18 строке `setAdditionalIconStyles` не используется теперь

2023-02-03 12:31 UTC, Irinaristova requested changes

2023-02-03 12:31 UTC, Irinaristova commented on src/components/Carousel/Carousel.fixture.tsx
> +        visibleItemCount={0}
зачем тут 0? если необходимо, чтобы отображались просто карточки по длине, то этот пропс просто можно не указывать

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +    const BORDER_STYLE =
это лучше вынести из компонента, т.к. это константа

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +        <BaseTile className="flex justify-between" title={tileTitle} image={tileImage}>
карточка должна быть кликабельна, нужно вернуть LinkWrapper

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +          <div className="h-full flex flex-col justify-between">
кусок с тайтлом и описание тоже нужно вернуть

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +          'relative p-7 min-w-[524px] h-full text-left box-border group-data-gray:bg-main-divider/50',
отступы по макету 12, а не 7

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +                className="text-xl-light flex flex-col flex-1 gap-2 max-w-[236px]"
это надо вернуть - pb-16 mb-3

2023-02-03 12:31 UTC, Irinaristova commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +            {socialMedia.length ? <SocialMedia className="pt-10 pb-0" media={socialMedia} /> : null}
тут убрать pt-10

2023-02-03 15:14 UTC, Longraf commented on src/components/Carousel/Carousel.fixture.tsx
> +        visibleItemCount={0}
`0` это автоширина каточки и вообще это фикстура, а не например дефолтные настройки карточки в целом не согласен с замечанием

2023-02-03 15:15 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +        <BaseTile className="flex justify-between" title={tileTitle} image={tileImage}>
Проверка была во время теста изменений, LinkWrapper был возвращён

2023-02-03 15:16 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +          <div className="h-full flex flex-col justify-between">
Проверка была во время теста изменений, уже вернул

2023-02-03 15:17 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +                className="text-xl-light flex flex-col flex-1 gap-2 max-w-[236px]"
Из каких соображений ?

2023-02-03 15:18 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +          'relative p-7 min-w-[524px] h-full text-left box-border group-data-gray:bg-main-divider/50',
По макету это 28px что соответствует `p-7` откуда там `p-12` взялось?

2023-02-03 15:18 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +            {socialMedia.length ? <SocialMedia className="pt-10 pb-0" media={socialMedia} /> : null}
Почему ?

2023-02-03 15:18 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +    const BORDER_STYLE =
Просьба уточнить что подразумевается под это ?

2023-02-03 15:18 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> -  <div className={style('flex', setAdditionalIconStyles(items))}>
Done

2023-02-06 08:19 UTC, Irinaristova approved these changes

2023-02-06 08:22 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +          'relative p-7 min-w-[524px] h-full text-left box-border group-data-gray:bg-main-divider/50',
Поправлено Эльдаром на p-7

2023-02-07 09:13 UTC, Mikage777 commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +  <div className={'absolute bottom-0 right-0'}>
```suggestion
  <div className="absolute bottom-0 right-0">
```

2023-02-07 09:14 UTC, Mikage777 commented on src/components/CarouselRecommendationCard/CarouselRecommendationCardContent.ts
> +import { TextAlign } from '../../ui-kit/Text/TextProps';
```suggestion
import type { TextAlign } from '../../ui-kit/Text/TextProps';
```

2023-02-07 09:14 UTC, Mikage777 approved these changes

2023-02-07 09:43 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCard.tsx
> +  <div className={'absolute bottom-0 right-0'}>
Done

2023-02-07 09:43 UTC, Longraf commented on src/components/CarouselRecommendationCard/CarouselRecommendationCardContent.ts
> +import { TextAlign } from '../../ui-kit/Text/TextProps';
Done

2023-02-07 09:43 UTC, merged