Add ExchangeRateOfficeBlock
redneckz/wildless-cms-uni-blocks pull request #1275
Opened 2023-02-01 08:41 UTC by AlexsaTasara

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +const CURRENCY_ICONS_MAP = {
Если есть перечень валют, которые могут быть использованы, константу можно типизировать.
Если, например, перечень валют для обмена будет в `enum`  `ExchangeCurrency`, по аналогии с `Currency` (ниже валют перечислено больше чем в `Currency`), то можно типизировать так:
```ts
const CURRENCY_ICONS_MAP: Record<keyof typeof ExchangeCurrency, IconName> = {
    USD: 'DollarIcon',
    ...
```
`IconName` лежит в `src/icons/IconName.ts`.
Тогда может будет сделать объект, где ключ - ключ в ExchangeCurrency, значение - название иконки

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  rest.currencies ? (fourRates = topNRates(rest.currencies, 4)) : null;
`currencies` можно деструктурировать из пропсов, так как он используется

```ts
export const ExchangeRateOffice = JSX<ExchangeRateOfficeProps>(({ className = '', currencies, ...rest }) => {
  let fourRates: CurrencyInformation[] = [];
  currencies ? (fourRates = topNRates(currencies, 4)) : null;
```

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  rest.currencies ? (fourRates = topNRates(rest.currencies, 4)) : null;
Здесь мутабельное изменение в `fourRates` не отслеживается, нужно использовать состояние, чтобы при изменении `fourRates` запускалась перерисовка компонента.

Инициализацию можно упростить
```ts
const fourRates:  CurrencyInformation[] = currencies ? topNRates(currencies, 4) : [];
```

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  let sdif = 0;
`lowerCamelCase` и название более понятное, без контекста ниже не сразу понятно назначение переменных.
bdif - buyDif / buyDelta
sdif - sellDif / sellDelta

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +const renderCurrencyRow = (exchangeCurrencyItem: CurrencyInformation) => {
Можно сразу сделать деструктуризацию с нужными пропами.
```ts
const renderCurrencyRow = ({ buyPrice, buyDifference, sellPrice, sellDifference, }: CurrencyInformation) => {
```

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  exchangeCurrencyItem?.sellDifference ? (sdif = exchangeCurrencyItem?.sellDifference) : null;
Аналогично fourRates выше, можно инициализацию совместить,
```ts
const buyDif = buyDifference ? buyDifference : 0;
const sellDif = sellDifference ? sellDifference : 0;
```

2023-02-01 20:34 UTC, Grimitsu commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  const textColsell = sdif >= 0 ? 'green' : 'red';
lowerCamelCase, 
textColBuy
textColSell
Предполагаю, что правила для vscode после ренейма не понадобятся, их можно будет убрать из белого списка

2023-02-08 08:42 UTC, vladeiko approved these changes

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +          <div className={`font-normal text-sm text-secondary-text ${TEXT_COLORS[textColBuy]}`}>
Проверить это везде

```suggestion
          <div className="font-normal text-sm text-secondary-text ${TEXT_COLORS[textColBuy]}">
```

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +  const textColSell = sellDif >= 0 ? 'green' : 'red';
`buyDif` и `sellDif` используются только для вычисления цвета. Их можно убрать.
Тогда можно записать вычисление иначе: `(buyDif || 0) >= 0 ?`

По цветам.
Если в переменных хранить стилевые атомы, то можно будет отказаться от `TEXT_COLORS`.

Далее можно прийти к выводу, что логичнее использовать утилиту `style` (см. примеры в других компонентах)
Получится что-то вроде:
```
className={style('font-normal text-sm text-secondary-text', (buyDifference || 0) >= 0 ? 'text-green' : 'text-red')}
```

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +        <div className="flex flex-col">
Проверить во всех местах.
Дочерним элементами данного `div` являются другие `div`. Это блочные элементы. Если убрать `flex flex-col`, то внешний вид поменяться не должен.

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +      </td>
Прошу заметить, что абсолютно такая же структура встречается и ниже, и выше. Значит, можно как-нибудь оптимизировать это дело

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +                  </th>
Подобная структура встречается много раз ниже. Значит, можно оптимизировать

2023-02-08 08:42 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +};
Функцию забыла переделать. Обговаривали как

2023-02-08 09:15 UTC, vladeiko requested changes
Вопросы будут - пиши

2023-02-08 09:59 UTC, vladeiko requested changes

2023-02-08 09:59 UTC, vladeiko commented on src/components/ExchangeRateOffice/ExchangeRateOffice.tsx
> +          <div className={`font-normal text-sm text-green`}>{buyOfficeName}</div>
Проверить это везде
```suggestion
          <div className="font-normal text-sm text-green">{buyOfficeName}</div>
```

2023-02-15 10:33 UTC, redneckz commented on src/components/ExchangeRateOffice/CurrencyProps.ts
> +export enum Currencies {
имя модуля не соответствует единственной сущности внутри

2023-02-15 10:34 UTC, redneckz approved these changes

2023-02-15 12:55 UTC, vladeiko approved these changes

2023-02-15 13:02 UTC, merged