Fixed styles
redneckz/wildless-cms-uni-blocks pull request #1382
Opened 2023-02-27 07:34 UTC by KolyaBlacK

2023-02-27 10:21 UTC, Mikage777 commented
Добавь пожалуйста ссылку на тикет в дескрипшен

2023-02-27 10:23 UTC, vladeiko requested changes
Блокирующее изменение. Почему полетел регресс в PromoTile и в VerticalLayout?

2023-02-27 10:23 UTC, vladeiko commented on src/components/Carousel/CarouselScrollButtons.tsx
> +      {scroll.canScrollLeft ? (
Может быть тогда проверка на 76 строке становится лишней? В смысле может оттуда тогда можно убрать эту часть: `scroll.canScrollLeft || scroll.canScrollRight`?

2023-02-27 10:25 UTC, vladeiko commented
Можно, пожалуйста, оформить по конвеншену реквест? Хотя бы ссылку на задачу

2023-02-27 10:25 UTC, vladeiko commented on src/components/CarouselRichTextCard/CarouselRichTextCard.tsx
> +    <BlockWrapper className={style('p-9 border border-gray h-full min-w-96', className)} {...rest}>
Почему накладывается атом `h-full`? Разве карусель сама не ставит дочерним элементам максимальную высоту?

2023-02-27 13:28 UTC, KolyaBlacK commented on src/components/CarouselRichTextCard/CarouselRichTextCard.tsx
> +    <BlockWrapper className={style('p-9 border border-gray h-full min-w-96', className)} {...rest}>
не ставит

2023-02-28 06:54 UTC, vladeiko approved these changes

2023-02-28 07:23 UTC, merged