Feature/footer mobile
redneckz/wildless-cms-uni-blocks pull request #1435
Opened 2023-03-06 14:29 UTC by KolyaBlacK

Мобильный блок Footer

...

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1394

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-06 14:52 UTC, vladeiko requested changes

2023-03-06 14:52 UTC, vladeiko commented on src/components/Footer/Footer.mobile.tsx
>      <BlockWrapper tag="footer" className={`px-4 py-[26px] ${className}`} {...rest}>
Поставь, пожалуйста, утилиту `style`

2023-03-06 14:52 UTC, vladeiko commented on src/components/Footer/HorizontalNavigationLink.mobile.tsx
> +        className={`hover:text-primary-main inline-block no-underline ${className}`}
Отличается от десктоп версии ТОЛЬКО набором атомов. Так что можно убрать мобильный `HorizontalNavigationLink`, из десктопного убрать все атомы и из мобильного и десктопного футеров передавать свой набор классов.
Либо через `isMobile` другой набор атомов

2023-03-06 14:52 UTC, vladeiko commented on src/components/Footer/SocialMedia.mobile.tsx
> +      <MediaButton key={String(index)} buttonSize="mobile" {..._} />
Так быть не должно. В таком случае следует:
1. Переопределять атомы, если возможно
2. Использовать подход через `isMobile`

2023-03-06 14:52 UTC, vladeiko commented on src/components/LinkList/LinkList.mobile.tsx
> +};
От десктопной версии отличаются только наборы атомов. Выше описывал варианты решения

2023-03-06 14:52 UTC, vladeiko commented on src/components/Footer/Footer.mobile.tsx
>              <LinkList documents={item.items} />
Компонент не должен здесь использоваться. `LinkList` - это полноценный блок, а не `ui-kit` элемент.
Варианты решения:
1. Если нигде на страницах не используется лишить его `BlockWrapper` и отправить в `ui-kit`
2. Если используется на каких-то страницах, то отправить его в `ui-kit` и завести отдельно блок под него по аналогии с `ButtonBlock`, `ImgBlock`, `RichTextBlock`

2023-03-06 14:52 UTC, vladeiko commented on src/components/MobileAppTile/MobileAppTile.mobile.tsx
> +        className={`col-span-12 rounded-md cursor-pointer p-4 bg-secondary-light font-sans ${className}`}
Используй утилиту `style`, пожалуйста

2023-03-06 14:52 UTC, vladeiko commented on src/components/RollupItem/RollupItem.mobile.tsx
> -  return version === 'primary' ? (
GitHub Actions / test (16.x)

'version' is defined but never used

2023-03-06 14:52 UTC, vladeiko commented on src/components/RollupItem/RollupItem.mobile.tsx
> +      className={`border-none bg-transparent flex items-center justify-between text-left w-full text-primary-text group/button cursor-pointer py-2 px-0`}
```suggestion
      className="border-none bg-transparent flex items-center justify-between text-left w-full text-primary-text group/button cursor-pointer py-2 px-0"
```

2023-03-06 14:55 UTC, vladeiko requested changes

2023-03-06 14:55 UTC, vladeiko commented on src/components/RollupItem/RollupItemContent.ts
> +    primaryIcon?: Picture;
Почему не просто `icon`? У этого элемента есть ещё и не основная иконка?

2023-03-06 14:55 UTC, vladeiko commented on src/components/LinkList/LinkList.mobile.tsx
> +  <BlockWrapper className={`my-3 ${className}`} {...rest}>
Используй утилиту `style`, пожалуйста

2023-03-06 14:58 UTC, vladeiko commented
У тебя будет конфликт с @Longraf в МРе, он тоже взаимодействовал с `RollupItem`. И совсем иначе, чем ты

2023-03-09 08:59 UTC, Longraf commented on src/components/RollupItem/RollupItem.mobile.tsx
>  import type { JSXBlock, UniBlockProps } from '../../model/JSXBlock';
Договорились всё что связано с RollupItem будет в моеём МР-е

2023-03-10 09:14 UTC, closed without merging