Add CarouselProgramsCard for mobile
redneckz/wildless-cms-uni-blocks pull request #1443
Opened 2023-03-09 11:48 UTC by andreySimonenko

## Что сделано?

Добавлен CarouselProgramsCard для мобильной версии

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1414

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-10 06:57 UTC, Longraf approved these changes

2023-03-10 06:57 UTC, Longraf commented on src/components/CarouselProgramsCard/CarouselProgramsCard.fixture.mobile.tsx
> +  <CarouselProgramsCard className="col-span-4" {...BUSINESS_CARD} version="secondary" />
`col-span-4` для мобилки это очень мало, посмотри регресс там снапшоты получились мягко говоря не очень. Регресс нужен для нас в первую очередь понять что "уехало" и пр а по таким мы ничего не поймём
![image](https://user-images.githubusercontent.com/32570545/224244019-04d1db48-f9e6-4898-bd2b-9b3cf79f5ebd.png)

2023-03-10 06:57 UTC, Longraf commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +          {title ? <Heading className="mb-2" headingType="h5" title={title} /> : null}
Есть сомнения по Heading правильно ли он отображается и вообще стоит ли этот МР вливать до МР-а с мобильной типографикой

2023-03-10 06:57 UTC, Longraf commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +    {_.title ? <div>{_.title}</div> : null}
Тут лучше description `<span>.............</span>` заменить на `<Text size="text-l" font="font-light">........</Text>`
c title тоже самое только не `Text` а `Paragraph`

2023-03-13 15:24 UTC, vladeiko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +    {_.title ? <div>{_.title}</div> : null}
Ни в коем случае.
Как раз `description` по семантике - это `Paragraph`, а `title` - это `Text`.
Сужу исходя строго из названий.
И тогда сразу вопрос: почему сначала идёт ОПИСАНИЕ, а потом ЗАГОЛОВОК?

2023-03-13 15:25 UTC, vladeiko requested changes

2023-03-13 15:25 UTC, vladeiko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +    {_.title ? <div>{_.title}</div> : null}
Это очень-очень странно

2023-03-15 08:33 UTC, Longraf commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +const renderList = (_: HeadlineCommonProps, i: number) => (
Функции максимально похожие, не надо дублировать надо выносить повторяющиеся компоненты либо выносить различающиеся части.
![image](https://user-images.githubusercontent.com/32570545/225251522-462ce579-da1b-49c1-af81-f1f4e22c0e25.png)

2023-03-15 08:33 UTC, Longraf commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +      <BlockWrapper className={style('border border-gray p-default', className)} {...rest}>
![image](https://user-images.githubusercontent.com/32570545/225251811-1d9e8847-0b90-43c0-a235-c80273bd06e0.png)
Компоненты очень похожие у них больше общего чем того что отличается

2023-03-15 12:26 UTC, redneckz commented
Надо обновить скрины. Скорее всего уже пофикшено сплющивание изображений

2023-03-15 12:28 UTC, redneckz commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +export const CarouselProgramsCard = JSX<CarouselTariffsCardProps>(
Ещё раз напомню, что лучше использовать резиновую вёрстку через модификаторы sm md lg xl
и гибкие flex.
Определять мобильные модули - в последнюю очередь

2023-03-15 12:28 UTC, redneckz commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +export const CarouselProgramsCard = JSX<CarouselTariffsCardProps>(
Причем надо выносить общие мелкие части и переопределять только то что нужно

2023-03-17 12:10 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.fixture.mobile.tsx
> +  <CarouselProgramsCard className="col-span-4" {...BUSINESS_CARD} version="secondary" />
поправил

2023-03-17 12:11 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +          {title ? <Heading className="mb-2" headingType="h5" title={title} /> : null}
++

2023-03-17 12:12 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +const renderList = (_: HeadlineCommonProps, i: number) => (
заменил на адаптивную верстку

2023-03-17 12:12 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +      <BlockWrapper className={style('border border-gray p-default', className)} {...rest}>
заменил на адаптивную верстку

2023-03-17 12:13 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.mobile.tsx
> +export const CarouselProgramsCard = JSX<CarouselTariffsCardProps>(
заменил на адаптивную верстку

2023-03-17 13:07 UTC, vladeiko approved these changes

2023-03-17 13:07 UTC, vladeiko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.tsx
> +          className="flex flex-col sm:flex-row sm:items-center"
Если тут `flex flex-col`, то скорее всего можно обойтись без него. Т.к. div'ы и так идут блочно. Скорее всего `flex` нужен только с модификатором `sm`

2023-03-17 13:33 UTC, andreySimonenko commented on src/components/CarouselProgramsCard/CarouselProgramsCard.tsx
> +          className="flex flex-col sm:flex-row sm:items-center"
++

2023-03-17 14:18 UTC, merged