add office details block
redneckz/wildless-cms-uni-blocks pull request #1462
Opened 2023-03-13 08:38 UTC by AlexsaTasara

## Что сделано?

Задача: https://github.com/redneckz/wildless-cms-uni-blocks/issues/811#

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/000

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-13 13:20 UTC, vladeiko requested changes
`OfficeDetails.ui.json` совсем пустой файл. Как минимум должно быть: `{}`
Т.к. используются кнопки с иконками надо подключить виджет. Можем посмотреть вместе. Хотя, если в CMS виджет для иконок появляется, то не надо

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.tsx
> +          {rest.kgrKo ? <div>{renderOfficeTable('КГР КО', rest.kgrKo)}</div> : null}
Не надо обращаться через `rest`, проведи явную деструктуризацию.
Зачем обёрнуты в `div`'ы все? Если рендер-функция возвращает `div`'ы всё равно

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.tsx
> +          {rest.correspondentAccountNumber ? (
Лучше явно деструктуризацию выполнить

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.tsx
> +      <div className={style('flex flex-col items-stretch')}>
Нет необходимости использовать `style` здесь

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.tsx
> +        <div className="flex flex-col">
Не вижу необходимости во `flex flex-col`, т.к. все вложенные элементы обёрнуты в `div`'ы, которые и так блочные

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.tsx
> +        'overflow-hidden p-9 box-border relative min-h-[364px] flex flex-col justify-between',
Не вижу необходимости во `flex flex-col`, т.к. все вложенные элементы обёрнуты в блочные элементы

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/renderOfficeTable.tsx
> +    </div>
С семантикой проблемы, т.к. не вижу тегов: `table`, `tr`. У таблицы вроде должны быть эти теги

2023-03-13 13:20 UTC, vladeiko commented on src/components/OfficeDetails/OfficeDetails.example.json
> +{}
Не хватает примера

2023-03-15 09:22 UTC, Longraf approved these changes

2023-03-15 09:22 UTC, Longraf commented on src/components/OfficeDetails/OfficeDetails.tsx
> +          className="!p-0 !bg-transparent z-10 mb-3.5"
Точно ли нужен important в этом атоме `!bg-transparent` ?

2023-03-15 09:22 UTC, Longraf commented on src/components/OfficeDetails/OfficeDetails.tsx
> +          <Text size="text-m-light" align="text-left" color="text-secondary-text">
`size="text-m" font="font-light"`

2023-03-15 12:37 UTC, redneckz commented on src/components/OfficeDetails/OfficeDetails.tsx
> +          className="!p-0 !bg-transparent z-10 mb-3.5"
вместо `!p-0` есть проп `isPadding={false}`

2023-03-15 12:37 UTC, redneckz commented on src/components/OfficeDetails/OfficeDetails.tsx
> +        'overflow-hidden p-9 box-border relative min-h-[364px]',
минимальная высота, как правило, не оправдана

2023-03-28 08:07 UTC, Mikage777 commented
Закрываю МР в связи с потерей актуальности в самой задаче. Задача в блоке предназначалась для страниц-филиалов (их карточек) которые планировалось генерить на уровне портала. В связи с недостаточностью данных из сервиса справочника, такие страницы сгенерировать невозможно.

2023-03-28 08:07 UTC, closed without merging