Add mobile ButtonsBlock
redneckz/wildless-cms-uni-blocks pull request #1464
Opened 2023-03-13 12:47 UTC by rmrth

## Что сделано?
Блок `ButtonBlock` переименован в `ButtonsBlock`, теперь в него можно передавать несколько кнопок.
Добавлена мобильная версия блока `ButtonsBlock`.

- [x] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1420

## Чек-лист для ревьюера

### Качество кода

- [x] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [x] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [x] Модули с высокой сложностью покрыты модульными тестами.
- [x] Нет "магических" констант.
- [x] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [x] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [x] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [x] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [x] Минимизирована вложенность элементов.
- [x] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [x] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-13 15:20 UTC, vladeiko requested changes
Очень странным образом полетел регресс у десктопных кнопок? Они точно должны превратиться в такие?

2023-03-13 15:20 UTC, vladeiko commented on src/components/ButtonsBlock/ButtonsBlockContent.ts
> +  buttons?: (ButtonWithIconProps | undefined)[];
Ты проверил какая схема сгенерировалась? По-моему, сгенерируется некорректная схема.
Не надо `| undefined`, как по мне явно лишнее.
Достаточно `buttons?: ButtonWithIconProps[]`

2023-03-14 08:25 UTC, rmrth commented on src/components/ButtonsBlock/ButtonsBlockContent.ts
> +  buttons?: (ButtonWithIconProps | undefined)[];
поправил

2023-03-14 09:26 UTC, redneckz commented on src/components/__snapshots__/Blocks.spec.tsx.snap
> +exports[`Blocks ButtonsBlock should render block "ButtonsBlock" without content 1`] = `
нужно переделать example

2023-03-14 09:29 UTC, redneckz commented on src/components/ButtonsBlock/ButtonsBlock.tsx
> +    {renderButtonsSection(buttons, { buttonClassName: 'w-full sm:w-auto' })}
хотелось бы отказаться от buttonClassName везде.
особенно на уровне блока.

2023-03-14 09:48 UTC, redneckz approved these changes

2023-03-14 12:36 UTC, vladeiko approved these changes

2023-03-14 13:00 UTC, rmrth commented on src/components/__snapshots__/Blocks.spec.tsx.snap
> +exports[`Blocks ButtonsBlock should render block "ButtonsBlock" without content 1`] = `
+

2023-03-15 03:34 UTC, merged