Add mobile calculator
redneckz/wildless-cms-uni-blocks pull request #1476
Opened 2023-03-15 06:09 UTC by vyacheslav-khalatov

## Что сделано?

Добавлен мобильный калькулятор

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1368

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-15 12:20 UTC, Longraf commented
main падает, нужно порешать конфликты и возможно обновить снапшоты `npm run test:update`

2023-03-15 12:59 UTC, Longraf requested changes

2023-03-15 12:59 UTC, Longraf commented on src/ui-kit/InputRange/InputRange.tsx
> +            isMobile ? 'text-base mt-1.5' : '',
1. `isMobile` не рекомендуется использовать. 
2. тут вполне возможно использовать константу 
3. атом `text-base` вообще ни на что не влияет. 
4. от `mt-1.5` тоже можно избавиться т.к. выше уже есть атом `mt-2`

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.fixture.mobile.tsx
> +import { Calculator } from './Calculator.mobile';
.mobile нигде в явном виде не указываем тут должно быть `import { Calculator } from './Calculator';`

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.fixture.mobile.tsx
> +import { ButtonWithIconProps } from '../../ui-kit/Button/ButtonProps';
type

2023-03-15 12:59 UTC, Longraf commented on src/components/Blocks.mobile.ts
> +import { Calculator } from './Calculator/Calculator.mobile';
```suggestion
import { Calculator } from './Calculator/Calculator';
```

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/BusinessDepositCalculatorForm.mobile.tsx
> +import { InputRangeProps } from '../../ui-kit/InputRange/InputRangeProps';
```suggestion
import type { InputRangeProps } from '../../ui-kit/InputRange/InputRangeProps';
```

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +import { CalculatorTab } from './CalculatorContent';
type

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +import { EmbeddableCalcBlocks } from './EmbeddableCalcBlocks.mobile';
импортов с `.mobile` не должно быть, он импортируется в не явном виде

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +          <BlockWrapper className="px-5 py-4">{renderCalculator(tab)}</BlockWrapper>
`px-5 py-4` очень похоже на `p-default`

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +        <div className="w-[44px] h-[44px] bg-white rounded-md flex justify-center items-center">
```suggestion
        <div className="w-11 h-11 bg-white rounded-md flex justify-center items-center">
```

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +        className="w-full px-5 py-4 bg-green flex items-center border-b border-white"
`px-5 py-4` очень похоже на `p-default`

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/CalculatorValueBlock.tsx
> +    <div className={style('mb-7', isMobile ? 'flex justify-between text-base' : '', className)}>
лучше использовать константу, пример можно найти в проекте 
![image](https://user-images.githubusercontent.com/32570545/225314238-8e584460-e258-4597-8dc2-1eebb5953c33.png)

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/CalculatorValueBlock.tsx
> +    <div className={style('mb-7', isMobile ? 'flex justify-between text-base' : '', className)}>
атом `text-base` нужно убрать он ни на что не влияет

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { DepositCalculatorProps } from './CalculatorContent';
type

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { UniBlockProps } from '../../model/JSXBlock';
type

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { UniBlockProps } from '../../model/JSXBlock';
Проверь пожалуйста все импорты где импортируются типы должно быть` import type`

2023-03-15 12:59 UTC, Longraf commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { JSX } from '@redneckz/uni-jsx';
КАТЕГОРИЧЕСКИ ЗАПРЕЩЕНО создавать файл `.mobile` если он хотя бы на 50% повторяет desktop-ный вариант

2023-03-15 13:06 UTC, Longraf requested changes

2023-03-15 13:06 UTC, Longraf commented on src/components/Calculator/CreditCalculatorForm.tsx
>  /* eslint-disable max-lines, max-lines-per-function */
![image](https://user-images.githubusercontent.com/32570545/225316988-736b1ff7-0cfd-4773-a773-f42cb7a887ea.png)
КАТЕГОРИЧЕСКИ ЗАПРЕЩЕНО создавать файл `.mobile` если он хотя бы на 50% повторяет desktop-ный вариант. Нужно либо повторяющиеся части выносить либо различающиеся, в данном случае тут скорее надо вынести атомы/молекулы которые отличаются

2023-03-16 07:46 UTC, vyacheslav-khalatov commented on src/components/Calculator/BusinessDepositCalculatorForm.mobile.tsx
> +        } as RenderWantedSumParams)}
линтер ругается, что в функцию передается any, хотя ожидается RenderWantedSumParams

2023-03-16 07:47 UTC, vyacheslav-khalatov commented on src/components/Calculator/BusinessDepositCalculatorForm.mobile.tsx
> +        <div className="mt-4 pb-4 border-b border-main-divider">
это нужно чтобы бордер не прилип к компоненту
можно padding убрать и добавить margin следующему компоненту

2023-03-27 11:50 UTC, Longraf requested changes

2023-03-27 11:50 UTC, Longraf commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { style } from '../../utils/style';
Стало лучше но дублирование повторяется 
![image](https://user-images.githubusercontent.com/32570545/227931539-0e1328c1-0d8f-4df4-b028-fcd925fa494f.png)

2023-03-27 11:50 UTC, Longraf commented on src/components/Calculator/EmbeddableCalcBlocks.mobile.tsx
> +import { BusinessDepositCalculatorForm } from './BusinessDepositCalculatorForm';
![image](https://user-images.githubusercontent.com/32570545/227932037-fda823fa-8453-47d3-aef9-62ba6d4cce51.png)
Дублирование

2023-03-27 11:50 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +  <BlockWrapper className={style('p-0', className)}>{renderTabs(calculatorTabs)}</BlockWrapper>
У BlockWrapper есть свойство defaultPadding для отступов

2023-03-27 11:50 UTC, Longraf commented on src/components/Calculator/CreditCalculatorForm.mobile.tsx
> +      <section className={style('flex flex-col gap-4', className)}>
![image](https://user-images.githubusercontent.com/32570545/227933140-09d650e9-74eb-422b-acd2-2bc431660c43.png)
Тут явно одно и тоже только в разных обёртках. В одном случае `<Rate>` в другом `<renderRate/>` вот для Rate видимо и надо делать мобильный вариант

2023-03-29 12:30 UTC, vyacheslav-khalatov commented on src/components/Calculator/CreditCalculatorForm.tsx
>  /* eslint-disable max-lines, max-lines-per-function */
Поправил

2023-03-29 12:31 UTC, vyacheslav-khalatov commented on src/components/Calculator/Calculator.mobile.tsx
> +  <BlockWrapper className={style('p-0', className)}>{renderTabs(calculatorTabs)}</BlockWrapper>
Поправил

2023-03-29 12:31 UTC, vyacheslav-khalatov commented on src/components/Calculator/CreditCalculatorForm.mobile.tsx
> +      <section className={style('flex flex-col gap-4', className)}>
Исправлено

2023-03-29 12:44 UTC, vyacheslav-khalatov commented on src/components/Calculator/DepositCalculatorForm.mobile.tsx
> +import { style } from '../../utils/style';
поправил

2023-03-30 08:09 UTC, vyacheslav-khalatov commented on mobile/package.json
> +      "limit": "45 kB",
Так там 40+ файлов для калькулятора и они все вошли вошли в бандл, если я правильно понимаю

2023-04-03 07:18 UTC, Longraf approved these changes

2023-04-03 07:18 UTC, Longraf commented on src/components/Calculator/Calculator.mobile.tsx
> +  }
Возможно для лучшей читабленость лучше дать имя например `const isSingleTab = tans.length === 1`

2023-04-03 07:39 UTC, Mikage777 commented on src/components/Calculator/Calculator.mobile.tsx
> +  }
++

2023-04-03 07:46 UTC, merged