Add BonusBenefitsBlock for mobile
redneckz/wildless-cms-uni-blocks pull request #1477
Opened 2023-03-15 08:41 UTC by andreySimonenko

## Что сделано?

добавлен мобильный блок BonusBenefitsBlock

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1440

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-15 08:58 UTC, Longraf requested changes

2023-03-15 08:58 UTC, Longraf commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +    <BlockWrapper
![image](https://user-images.githubusercontent.com/32570545/225257667-0eb67d1c-5da1-4a5e-8fdc-32f5cd939546.png)
Дублирование необходимо выносить либо различающиеся куски кода, либо отличающиеся просто создать .mobile и сделать несколько правок это не верно

2023-03-15 08:58 UTC, Longraf commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +const renderBonusBenefit = ({ icon, title, description }: BonusBenefit, i: number) => {
![image](https://user-images.githubusercontent.com/32570545/225258267-4f26ace2-02f0-4fc7-8f24-543c14d09621.png)
Дулирование

2023-03-15 12:31 UTC, redneckz commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      className={`font-sans text-primary-text bg-white p-default flex flex-col text-center ${className}`}
необходимо использовать утилиту style вместо таких интерполяций

2023-03-15 12:32 UTC, redneckz commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      className={`font-sans text-primary-text bg-white p-default flex flex-col text-center ${className}`}
font-sans text-primary-text bg-white не требуется, так как применяется ко все блокам по умолчанию

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      {icon ? <Img image={icon} height="180" className="w-auto" /> : null}
уточнил у Эльдара, тут нужен фикс

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +    <BlockWrapper
++

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +const renderBonusBenefit = ({ icon, title, description }: BonusBenefit, i: number) => {
++

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      <Headline className="!p-0 mb-4" title={title} description={subtitle} headlineVersion="M" />
++

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      className={`font-sans text-primary-text bg-white p-default flex flex-col text-center ${className}`}
убрал

2023-03-15 13:41 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/BonusBenefitsBlock.mobile.tsx
> +      className={`font-sans text-primary-text bg-white p-default flex flex-col text-center ${className}`}
++

2023-03-16 07:24 UTC, Longraf approved these changes

2023-03-16 07:24 UTC, Longraf commented on src/components/BonusBenefitsBlock/renderBonusBenefit.tsx
> +  console.log('>>>>>>>', icon);
log надо удалить)

2023-03-16 07:24 UTC, Longraf commented on src/components/BonusBenefitsBlock/renderBonusBenefit.tsx
> +export const renderBonusBenefit = ({ icon, title, description }: BonusBenefit, i: number) => {
Можно короче без return `() => ()`

2023-03-16 07:24 UTC, Longraf commented on src/components/BonusBenefitsBlock/renderBonusBenefits.tsx
> +import { AlignType } from '../../model/AlignType';
type ?

2023-03-16 07:24 UTC, Longraf commented on src/components/BonusBenefitsBlock/renderBonusBenefits.mobile.tsx
> +import { AlignType } from '../../model/AlignType';
type

2023-03-17 12:55 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/renderBonusBenefit.tsx
> +export const renderBonusBenefit = ({ icon, title, description }: BonusBenefit, i: number) => {
++

2023-03-17 12:55 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/renderBonusBenefit.tsx
> +  console.log('>>>>>>>', icon);
++

2023-03-17 12:57 UTC, andreySimonenko commented on src/components/BonusBenefitsBlock/renderBonusBenefits.tsx
> +import { AlignType } from '../../model/AlignType';
++

2023-03-17 14:09 UTC, merged