Add Tile ProductBlock ProductBlockContainer
redneckz/wildless-cms-uni-blocks pull request #15
Opened 2022-05-27 14:50 UTC by andreySimonenko

2022-05-30 07:47 UTC, michaelkutuzov requested changes

2022-05-30 07:47 UTC, michaelkutuzov commented on src/Tile.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Мне кажется, что это не совсем то, чего ждёт от нас бизнес))
![image](https://user-images.githubusercontent.com/20220032/170937046-1ed64fee-f448-48b1-8e1d-2a188f310fd4.png)

Надо бы c флексом и автопереносом пошаманить, так думаю.

2022-05-30 07:47 UTC, michaelkutuzov commented on src/Tile.fixture.tsx
> +          'Кредитный лимит до 10 млн Р',
Лучше использовать значок рубля. Если шрифт его поддерживает, то это "&#8381; "

Если не поддерживает, то вот хак https://www.pandoge.com/stati-i-sovety/krossbrauzernyy-znachok-rublya-na-css

2022-05-30 07:47 UTC, michaelkutuzov commented on src/Tile.tsx
> +import type { ContentPageContext } from './ContentPageContext';
Возможно я не лучшим образом выразился при обсуждении, когда говорил о вариантах плиток в cosmos, но я подразумевал все различные(sic!) варианты. Ненужные я удалил.

2022-05-30 07:47 UTC, michaelkutuzov commented on src/Tile.tsx
> +import { Img } from './Img';
Также проверь, пожалуйста, все текста на overflow и переносы.

2022-05-30 07:47 UTC, michaelkutuzov commented on src/Tile.fixture.tsx
> +        image={image}
Картинку стоит подрезать так, чтобы нижний край изображения был вровень с кнопкой. Сейчас у неё белая полоска внизу и создаётся впечатление кривого выравнивания.

2022-05-31 10:54 UTC, andreySimonenko commented on src/Tile.tsx
> +import { JSX } from '@redneckz/uni-jsx';
поместил картинку  в сетку блока

2022-05-31 10:54 UTC, andreySimonenko commented on src/Tile.fixture.tsx
> +          'Кредитный лимит до 10 млн Р',
заменил на символ

2022-05-31 10:54 UTC, andreySimonenko commented on src/Tile.fixture.tsx
> +        image={image}
заменил картинку

2022-05-31 11:51 UTC, michaelkutuzov approved these changes

2022-05-31 11:51 UTC, michaelkutuzov approved these changes

2022-05-31 12:00 UTC, merged