Fix benfit bloc iconBgColor and size
redneckz/wildless-cms-uni-blocks pull request #1519
Opened 2023-03-20 14:16 UTC by Longraf

## Что сделано?
Шрифты в RollupItem меняются через конфиг
Изменён конвеншн IconBgVersion сейчас `secondary-light` не используется так что миграция не нужна
RoundedIcon Теперь принимает размер не для Inner а для самого RoundedIcon 
BenefitBlock теперь принимает версию заднего фона иконки и размер

...

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки
https://github.com/redneckz/temp_wcms/issues/975

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-21 08:16 UTC, Irinaristova requested changes

2023-03-21 09:46 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +    {benefit?.icon?.src ? <Img image={benefit.icon} /> : null}
Done

2023-03-21 10:24 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +        <div className="sm:flex sm:flex-wrap w-full sm:justify-center mt-8 gap-xxl" role="list">
gap не убран, он заменён на gap-xxl

2023-03-21 10:50 UTC, Irinaristova approved these changes

2023-03-22 10:39 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.example.json
> +        "iconBgVersion": ""
Если пустая строка, то может вообще тогда не указывать?

2023-03-22 10:40 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.tsx
Импорты не отсортированы (как минимум импорт `JSX` функции. Что-то сломалось

2023-03-22 11:07 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.example.json
> +        "iconBgVersion": ""
Если ничего не указывать в КР и будет пустая строка а не фараз "По умолчанию"

2023-03-22 11:53 UTC, merged