1437-mobile-carousel-links
redneckz/wildless-cms-uni-blocks pull request #1527
Opened 2023-03-21 14:21 UTC by artem1426

## Что сделано?

Мобильный блок СarouselLinks.
...

- [x] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/1437

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-03-22 07:55 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.fixture.tsx
> +      className={'p-10'}
Не надо задавать подобные атомы в фикстуре т.к. редакторы их так не будут заводить

2023-03-22 07:55 UTC, Longraf commented on src/components/Carousel/Carousel.tsx
> -    isPadding = true,
После удаления, не поломаются ли уже добавленные блоки и может требуется миграция ?

2023-03-22 07:55 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +            'flex flex-col max-w-96 text-white text-xl-light mb-5 sm:mb-0',
`text-xl-light` запрет на этот атом обязательно заменить на `text-xl font-light`

2023-03-22 07:55 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +              className="pt-6"
```suggestion
              className="pt-s"
```

2023-03-22 07:55 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +      className={'sm:min-w-[832px] sm:w-[832px] min-w-[350px] p-0 sm:p-7'}
Не надо заводить столько уникальных атомов. Лучше совсем отказаться от ограничения ширины sm:min-w-[832px] sm:w-[832px] min-w-[350px]

2023-03-22 07:55 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +            'flex flex-wrap self-start sm:min-w-[672px] sm:ml-12 sm:mr-10 min-w-[270px]',
Ещё пачка уникальных атомов. Это явный перебор sm:min-w-[672px] min-w-[270px]

2023-03-22 07:55 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +  'bg-transparent border-white border h-[70px] absolute min-w-[316px] top-0';
Ещё уникальные атомы их количество обязательно минимизировать в идеале вообще не использовать h-[70px]  min-w-[316px]

2023-03-22 07:55 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +          'relative group/link cursor-pointer min-w-[260px] h-[60px] sm:min-w-[328px] sm:h-[82px]',
Писал выше min-w-[260px] h-[60px] sm:min-w-[328px] sm:h-[82px]

2023-03-22 07:55 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +            'rounded-md sm:rounded-none min-w-[258px] h-[48px] sm:ml-3 sm:min-w-[316px] sm:h-auto',
Выше уже писал min-w-[258px] h-[48px] sm:ml-3 sm:min-w-[316px

2023-03-22 07:58 UTC, artem1426 commented on src/components/Carousel/Carousel.tsx
> -    isPadding = true,
уже добавленные блоки не поломались

2023-03-27 12:24 UTC, Longraf commented
Просьба обновить main

2023-03-28 14:07 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +const LINK_CLASS_NAME = `absolute border border-primary-main px-6 py-5
именованные метрики т.к. xl и lg переименованы обратно в цифры, так делать не надо !

2023-03-28 14:07 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +            'rounded-md sm:rounded-none w-full h-12 sm:ml-3 sm:w-full sm:h-auto',
```suggestion
            'rounded-md sm:rounded-none w-full h-12 sm:ml-s sm:w-full sm:h-auto',
```

2023-03-28 14:09 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +  const maxLinksCount = document.body.clientWidth > 640 ? MAX_LINKS_COUNT : MAX_LINKS_COUNT_MOBILE;
Есть большие сомнения в правильности подхода, попрошу его кого-нибудь посмотреть

2023-03-28 14:12 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +              <LinkButton key={String(index)} className="sm:m-1" {...link} />
Нужно использовать именованные метрики `m-2xs`

2023-03-28 14:12 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +  const itemCount = Math.ceil(links.length / maxLinksCount);
Не понимаю зачем вычислять icemCount и передавать его в Карусель, если там он и так вычисляется

2023-03-28 14:13 UTC, artem1426 commented on src/components/CarouselLinks/CarouselLinks.tsx
> +          className={style('flex flex-wrap self-start sm:w-[672px] w-full sm:ml-12 sm:mr-10')}
на счет жесткой ширины, не вижу быстрых способ отказаться от нее

2023-03-28 14:15 UTC, Longraf commented
![image](https://user-images.githubusercontent.com/32570545/228267019-8753c304-bf5d-4601-85d7-88a0d9b4ec67.png)
Это надо поправить !

2023-03-28 14:33 UTC, Longraf requested changes

2023-03-28 14:33 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +  const maxLinksCount = document.body.clientWidth > 640 ? MAX_LINKS_COUNT : MAX_LINKS_COUNT_MOBILE;
Не используем нативный api на портале при билде статики билд упадёт
Почему >640?
А если в конфиге поменяем, по всему проекту magic numbers переписывать?
Зачем вообще ограничение на количество links?

2023-03-29 07:42 UTC, artem1426 commented on src/ui-kit/LinkButton/LinkButton.tsx
> +          'relative group/link cursor-pointer w-64 h-16 sm:w-[47%] sm:h-20 sm:mr-4',
это сделано для слоев
![image](https://user-images.githubusercontent.com/76048968/228461874-ce47b69d-d248-4ead-90b5-9f95b1af1e18.png)

2023-03-30 06:39 UTC, Longraf approved these changes

2023-03-30 06:39 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.fixture.mobile.tsx
> +      className={'flex-col'}
Этот атом надо убрать т.к. редактор не может его поставить

2023-03-30 06:39 UTC, Longraf commented on src/components/CarouselLinks/CarouselLinks.tsx
> +          className={style('flex flex-wrap self-start sm:w-[672px] w-full sm:mx-10')}
mx-10 используем именованные метрики

2023-03-30 06:39 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.fixture.mobile.tsx
> +    <div className="flex justify-center p-10 max-w-sm">
Эти атомы редакторы не добавляют, из тех что тут представлены нужно убрать все

2023-03-30 06:39 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
> +          'relative group/link cursor-pointer w-64 h-16 sm:w-[47%] sm:h-20 sm:mr-4',
mr-4 заменить на именованную метрику

2023-03-30 06:39 UTC, Longraf commented on src/ui-kit/LinkButton/LinkButton.tsx
>                className="w-4 h-4 min-w-4 min-h-4 rounded-full box-border brightness-0 group-hover/link:brightness-100"
вместо min-w возможно ли использовать `object-fit` ?

2023-03-30 07:49 UTC, merged