Fix Bonusblock styles
redneckz/wildless-cms-uni-blocks pull request #1715
Opened 2023-04-20 16:59 UTC by Irinaristova

## Что сделано?

Исправлена верстка для релевантного отображения в кр

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/temp_wcms/issues/1045
https://github.com/redneckz/temp_wcms/issues/1044

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.
- [ ] Cтилевые часто используемые константы вынесены в отдельный модуль вида - `somethingStyle` | `somethingStyleMap`.

2023-04-21 06:23 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.tsx
>    return description && benefitType ? (
У тебя не работает линтер. Настрой, пожалуйста.
![image](https://user-images.githubusercontent.com/46086126/233556317-d4a76bd6-fd83-47c3-ad7e-cc047e0fc1fd.png)

2023-04-21 06:23 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +    <div className="mt-xs text-l font-light text-secondary-text group-data-secondary:text-white/80">
Нельзя отказаться от управления типографикой на этом уровне и перенести управление типографикой на уровень ниже? (в рендер-функции, например, поместив при этом управление типографикой в константу)

2023-04-21 06:51 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +        <div className="flex flex-wrap w-full md:justify-center mt-xl gap-5xl" role="list">
mt-xl лучше убрать и и поставить space-y-xl для родителя

2023-04-21 07:08 UTC, Irinaristova commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +        <div className="flex flex-wrap w-full md:justify-center mt-xl gap-5xl" role="list">
он тут не нужен, тк добавляет лишние отступы

2023-05-03 09:25 UTC, vladeiko requested changes

2023-05-03 09:25 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +import { AlignStyles } from '../../model/AlignStyles';
Вот эта вот непонятная константа зачем?

2023-05-03 09:25 UTC, vladeiko commented on cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/BenefitsBlock_list-base.png
Точно ли так должно быть?

![image](https://user-images.githubusercontent.com/46086126/235879194-a7d04d6e-f8de-4ce8-9776-d3a23a7b5495.png)

2023-05-03 09:25 UTC, vladeiko commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +    {description?.name || null}
То есть будет рендерить пустые текстовые теги?

2023-05-03 11:21 UTC, Irinaristova commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +import { AlignStyles } from '../../model/AlignStyles';
это общее решение для нескольких компонентов, было вынесено в модель для выравнивания Heading в мобильной версии и десктопе

2023-05-03 14:39 UTC, merged