Fix InnerTable styles
redneckz/wildless-cms-uni-blocks pull request #2001
Opened 2023-06-22 15:16 UTC by Irinaristova

## Что сделано?

Мобильный блок Таблица тарифов. Вложенная таблица. 
Исправлены замечания по верстке во вложенной таблице в мобильной версии

- [x] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/temp_wcms/issues/1295

## Чек-лист для ревьюера

### Качество кода

- [ ] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [ ] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [ ] Модули с высокой сложностью покрыты модульными тестами.
- [ ] Нет "магических" констант.
- [ ] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы. Для описания событий достаточно частичной декларации в духе client-driven contract (см. PreventableEvent).

### Качество вёрстки

- [ ] Крупные фрагменты вёрстки декомпозированы на приватные render функции.
- [ ] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [ ] Минимизировано использование уникальных и кастомных атомов вида - `prefix-[value]`.
- [ ] Минимизирована вложенность элементов.
- [ ] Минимизировано использование `flex-col` (обычно, можно обойтись блочными элементами).
- [ ] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.
- [ ] Cтилевые часто используемые константы вынесены в отдельный модуль вида - `somethingStyle` | `somethingStyleMap`.

2023-06-23 06:32 UTC, vladeiko requested changes

2023-06-23 06:32 UTC, vladeiko commented on src/ui-kit/InnerTable/InnerTableBody.tsx
> +import { AlignStyles } from '../../model/AlignStyles';
Этого быть не должно. Ни в `model`, ни вообще в принципе

2023-06-23 06:32 UTC, vladeiko commented on src/ui-kit/InnerTable/InnerTableBody.tsx
> +import { AlignStyles } from '../../model/AlignStyles';
Надо избавиться совсем и с концами

2023-06-23 11:39 UTC, Longraf commented on src/ui-kit/InnerTable/InnerTableBody.tsx
> +import { AlignStyles } from '../../model/AlignStyles';
@vladeiko Я не согласен. В связи с тем что у нас в десктоп варианте часто выравнивание по центру, а в мобилке по левому краю непонятно тогда как ты предлагаешь обратаываться этот вариант. Об этом уже говорил с Ксенией 
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/563f1913-697b-4736-95a2-8714cffb6330)

2023-06-27 10:19 UTC, Longraf requested changes

2023-06-27 10:19 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
>  import { JSX } from '@redneckz/uni-jsx';
Видно по регрессу что что-то пошло не так . Уверен что овнеры придут и заставят править
![image](https://github.com/redneckz/wildless-cms-uni-blocks/assets/32570545/b350c728-8ce9-4e31-b6bd-680b837bc07b)

2023-06-27 10:19 UTC, vladeiko approved these changes

2023-06-29 08:15 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
>  import { JSX } from '@redneckz/uni-jsx';
Регресс уже лучше, но заголовки всё ещё неверно отцентрованы

2023-06-29 08:16 UTC, vladeiko commented on cypress/snapshots/base/blocksVisualRegressionDesktop.cy.ts/StepsBlock_4 steps-base.png
Ожидаемый регресс?
Во всех Steps снапшотах ожидаемый ли регресс? Так задумано?

2023-07-04 08:10 UTC, Longraf approved these changes

2023-07-04 08:10 UTC, Longraf commented on src/components/Bonus/Bonus.tsx
> -          align={align}
text-left lg:text-center

2023-07-04 08:10 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
>  import { JSX } from '@redneckz/uni-jsx';
Десктопные блоки BenefitsBlock BonusBenefitBlock Bonus GraceBlock всё ещё неверный регресс по центрированию заголовков.

2023-07-04 09:24 UTC, Irinaristova commented on src/components/BenefitsBlock/BenefitsBlock.tsx
>  import { JSX } from '@redneckz/uni-jsx';
договорились, что во всех компонентах, кроме блока ошибки, блока шагов заголовок всегда будет слева

2023-07-04 09:24 UTC, Irinaristova commented
Договорились, что во всех компонентах, кроме блока ошибки, блока шагов заголовок всегда будет слева

2023-07-12 06:08 UTC, vladeiko requested changes
Регресс неприемлемый

2023-07-21 11:42 UTC, closed without merging