Update project a11y
redneckz/wildless-cms-uni-blocks pull request #2140
Opened 2023-08-10 09:27 UTC by Irinaristova

## Что сделано?

...

- [ ] С отчетом визуального регресса ознакомлен, подтверждаю связанные изменения (если применимо)

## Ссылка на тикет и прочие ссылки

https://github.com/redneckz/wildless-cms-uni-blocks/issues/000

## Чек-лист для ревьюера

### Качество кода

- [x] НЕТ использования `React` (только `@redneckz/uni-jsx`).
- [x] НЕТ использования типов DOM событий. Частичная типизация событий (см. PreventableEvent).
- [x] Имена (констант, переменных, функций, компонент, и т.д.) специфичны и дают описание на уровень выше имплементации.
- [x] Имена файлов отражают имена ключевых экспортируемых сущностей 1-1.
- [x] Модули с высокой сложностью покрыты модульными тестами (хуки в т.ч.).
- [x] Нет "магических" констант.
- [x] Аргументы публичных и приватных функций (в т.ч. обработчиков) - типизированы.

### Качество вёрстки

- [x] Крупные компоненты декомпозированы на render функции.
- [x] Используются общие стилевые константы (цвета, размеры, отступы, и т.д.).
- [x] Минимизировано использование редких или кастомных атомов вида - `prefix-[value]`.
- [x] Минимизирована вложенность элементов.
- [x] Минимизировано использование `flex-col` (как правило, можно обойтись блочными элементами).
- [x] Большая часть generic элементов (`div`/`span`) снабжена атрибутами `role`/`aria`.

2023-08-10 16:14 UTC, vladeiko requested changes

2023-08-10 16:14 UTC, vladeiko commented on src/components/ApplicationForm/renderSubmitButton.tsx
> +  <Button className={style('w-full @xl:w-auto', className)} type="submit" role="button">
Внутри находится тэг `button`, ему нет необходимости проставлять `role="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/Calculator/Calculator.mobile.tsx
> +        role="button"
Тэгу `button` не нужно проставлять `role="button"` и `type="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/Calculator/Calculator.tsx
> +      role="button"
Тэгу `button` не нужно проставлять `role="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/CardTransfer/CardTransfer.tsx
> +            <Button role="button" className="w-full mt-lg" type="submit" disabled={isDisabled}>
Тэгу `button` не нужно проставлять `role="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/CarouselTariffsCard/CarouselTariffsCard.tsx
> +    type="button"
Тэгу `button` не нужно проставлять `role="button"` и `type="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/ComparisonTable/ComparisonTable.tsx
> +        type="button"
Тэгу `button` не нужно проставлять `role="button"` и `type="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/ContentPage/ContentPage.fixture.tsx
> +      type="button"
Тэгу `button` не нужно проставлять `role="button"` и `type="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/Depository/DepositoryFilter.tsx
> +          role="button"
Внутри находится тэг `button`, ему нет необходимости проставлять `role="button"`

2023-08-10 16:14 UTC, vladeiko commented on src/components/Footer/Footer.mobile.tsx
> +      <div className="mb-lg pb-xs border-b border-main-divider" role="menu">
> A menu generally represents a grouping of common actions or functions that the user can invoke. The menu role is appropriate when a list of menu items is presented in a manner similar to a menu on a desktop application. Submenus, also known as pop-up menus, also have the role menu.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role

2023-08-10 16:14 UTC, vladeiko commented on src/components/Footer/Footer.mobile.tsx
> +      role="menuitem"
См. выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/DropdownMenu.tsx
> +        type="button"
Выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/DropdownMenu.tsx
> +        role="menuitem"
Выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/DropdownMenu.tsx
> +      role="menu"
Точно ли `menu`?

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/HeaderSecondaryMenu.tsx
> +      <div className={style('flex items-center gap-lg', className)} role="menu">
Точно ли меню или это всё-таки `nav`

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/HeaderSecondaryMenuButton.tsx
> +      role="button"
Выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/HeaderSubMenu.tsx
> +          role="menu"
Проверь не `nav` ли

2023-08-10 16:14 UTC, vladeiko commented on src/components/Header/HeaderTop.tsx
> +      type="button"
Выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/InsuranceAmountBlock/InsuranceAmountBlock.tsx
> +      role="button"
выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/InsuranceAmountBlock/InsuranceAmountBlockInner.tsx
> +      role="button"
выше

2023-08-10 16:14 UTC, vladeiko commented on src/components/OfficesAtmsMap/renderFoldButton.tsx
> +    type="button"
Выше

2023-08-10 16:14 UTC, vladeiko commented on src/ui-kit/Foldable/Foldable.tsx
>          {buttonNode}
А кнопка в таком случае тоже `listitem`?
А если нет, то будет ошибка, что в списке не элемент списка

2023-08-10 16:56 UTC, Irinaristova commented on src/components/ContentPage/ContentPage.fixture.tsx
> +      type="button"
A button with no type attribute acts as type="submit" -  поэтому необходимо добавлять тип

2023-08-11 06:40 UTC, vladeiko commented
Десктоп. По идее всё, кроме `Contrast` можно починить (но это не точно)
<img width="647" alt="image" src="https://github.com/redneckz/wildless-cms-uni-blocks/assets/46086126/1e30df7b-5e3c-432d-b71d-f19480a8207b">

Это мобильные результаты. По идее тоже можно всё починить (тоже не точно)
<img width="648" alt="image" src="https://github.com/redneckz/wildless-cms-uni-blocks/assets/46086126/825b81fd-b0b6-4f1d-a1ec-3faba70b94bd">

2023-08-11 08:55 UTC, vladeiko commented on cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/ComparisonTable_default-base.png
Регресс

2023-08-11 08:55 UTC, vladeiko commented on cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/ComparisonTable_with swiper-base.png
Регресс

2023-08-15 06:23 UTC, vladeiko commented on cypress/snapshots/base/blocksVisualRegressionMobile.cy.ts/ComparisonTable_default-base.png
Всё ещё отличия есть, хоть уже и не выглядит сломанным. Как по мне: новый вариант даже приятнее глазу (карточки). А вот смещение заголовка существенно

2023-08-15 06:23 UTC, vladeiko commented on src/components/ProductGallery/ProductGallery.tsx
> +        <nav className="h-28 px-xs mt-m -mb-m flex gap-xs box-border">
Вообще не уверен, что тут можно использовать `nav`. 

Судя по тому, что сказано тут https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav, следует использовать в `Header`. Где список порталов (частным, бизнес, свое) и ещё в нижнем меню, где список ссылок внутри портала

2023-08-15 06:23 UTC, vladeiko commented on src/components/StickyBottomMenu/ActiveSubMenuItem.tsx
> +      role="link"
Точно ли тэгу `a` необходимо указывать такую роль? Я уверен, что нет

2023-08-15 06:23 UTC, vladeiko commented on src/ui-kit/ApplicationFormLayout/ApplicationFormLayout.tsx
> +      <div className="container max-w-[978px] space-y-lg" role="form">
А там внутри не используется реальный тег `form`?

2023-08-18 06:46 UTC, vladeiko approved these changes

2023-08-18 06:47 UTC, merged