Feature/eslint condition rule
redneckz/wildless-cms-uni-blocks pull request #263
Opened 2022-08-25 11:24 UTC by end0rfin

Реализовал пользовательское правило для линтера (черновая версия) по задаче "[Lint] Правило для логических вычислений в вёрстке"
https://github.com/redneckz/temp_wcms/issues/158

2022-08-27 10:05 UTC, michaelkutuzov requested changes

2022-08-27 10:05 UTC, michaelkutuzov commented on eslint-rules/src/transformToTernaryRule/transformToTernaryRule.ts
> +    const isNodeValid = (node) => {
```js
    const getInvalidNodesLocations = (node) => {
      const type = node.declaration?.type || '';
      if (type === 'VariableDeclaration') {
        const { tokensAndComments: tokens } = context.getSourceCode();

        return tokens
          .filter(
            (_, i) =>
              _.type === 'Punctuator' &&
              _.value === '&&' &&
              tokens[i - 1]?.type === 'Identifier' &&
              tokens[i + 1].type === 'Punctuator' &&
              tokens[i + 1].value === '<' &&
              tokens[i + 2].type === 'JSXIdentifier',
          )
          .map((_) => _.loc);
      }
    };
```

2022-08-27 10:09 UTC, michaelkutuzov requested changes

2022-08-27 10:09 UTC, michaelkutuzov commented on eslint-rules/src/transformToTernaryRule/transformToTernaryRule.ts
> +      ExportNamedDeclaration(node) {
```js
      ExportNamedDeclaration(node) {
        const invalidLocations = getInvalidNodesLocations(node);

        if (invalidLocations && invalidLocations.length) {
          invalidLocations.forEach((_) => {
            context.report({
              node,
              messageId: 'default',
              loc: _,
            });
          });
        }
      },

2022-08-28 06:57 UTC, michaelkutuzov requested changes

2022-08-28 06:57 UTC, michaelkutuzov commented on .eslintrc.cjs
>              ],
И разумно сразу поправить найденные правилом ошибки

2022-08-28 19:53 UTC, end0rfin commented on eslint-rules/src/transformToTernaryRule/transformToTernaryRule.ts
> +    const isNodeValid = (node) => {
Благодарю за более лаконичный код. Исправил.

2022-08-28 19:54 UTC, end0rfin commented on eslint-rules/src/transformToTernaryRule/transformToTernaryRule.ts
> +      ExportNamedDeclaration(node) {
Благодарю за более лаконичный код. Исправил.

2022-08-28 19:54 UTC, end0rfin commented on .eslintrc.cjs
>              ],
Работа в этом направлении идёт ))

2022-08-29 21:13 UTC, vladeiko commented on eslint-rules/src/transformToTernaryRule/transformToTernaryRule.meta.ts
> +      'Конструкцию вида "variableName && <tagName />" трансформируйте с использованием тернарного оператора - "variableName ? <tagName> : null"',
Заменил бы ```variableName``` на ```condition```

2022-08-31 14:07 UTC, Irinaristova approved these changes

2022-09-13 13:57 UTC, michaelkutuzov approved these changes

2022-09-13 13:59 UTC, merged