Feature/block with tabs
redneckz/wildless-cms-uni-blocks pull request #269
Opened 2022-08-25 15:33 UTC by lis42000

- Добавлен блок с табами навигации
- Добавлена поддержка якоря

2022-08-25 15:50 UTC, Grimitsu commented on src/components/NavigatorTabs/NavigatorTabsContent.ts
> +   * @minItems 3
3 таба минимум без ограничений?

2022-08-26 10:05 UTC, lis42000 commented on src/components/NavigatorTabs/NavigatorTabsContent.ts
> +   * @minItems 3
Обсудили с дизайнером, решили что так и будет

2022-08-26 11:10 UTC, vladeiko commented on src/components/NavigatorTabs/NavigatorTabs.tsx
> +  console.log(navigatorTabs);
Лишний лог

2022-08-26 11:15 UTC, vladeiko commented on src/components/NavigatorTabs/NavigatorTabs.tsx
> +    ? tabs.map((tab) => (
Вот тут проверка на длину, хотя в ```NavigatorTabs``` уже выполняется проверка на существование. Если длина нулевая, то ничего и не отрендерится.

Я бы назвал эту функцию ```renderTab```, а в NavigatorTabs сделал бы так:
```
{navigatorTabs ? navigatorTabs.map(renderTab) : null}
```

2022-08-26 11:15 UTC, vladeiko commented on src/components/NavigatorTabs/NavigatorTabs.tsx
> +    ? tabs.map((tab) => (
Если надо передать hash, то можно каррирование сделать

2022-08-26 12:22 UTC, michaelkutuzov commented
«Название выбранной вкладки должно окраситься в зеленый цвет (зеленым цветом выделяется только активная вкладка)
Сам блок с табами должен также сместиться и отобразиться над блоком, к которому был выполнен скролл.
Если пользователь самостоятельно скроллит страницу БЕЗ клика на название вкладки - вышеописанные действия с блоком табов должны также производиться, т.е. при достижении следующего блока страницы блок с табами отображается над этим блоком, соответствующая вкладка блока табов меняет цвет на зеленый.»

Этого не наблюдается

2022-08-26 12:24 UTC, michaelkutuzov requested changes

2022-08-26 12:24 UTC, michaelkutuzov commented on src/components/NavigatorTabs/NavigatorTabs.example.json
> +    { "label": "Tab1", "anchor": "tab1" },
Лучше заполнять данными с макета, проще по PP проверять

2022-08-26 12:25 UTC, michaelkutuzov requested changes

2022-08-26 12:25 UTC, michaelkutuzov commented on src/components/NavigatorTabs/NavigatorTabItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
https://github.com/redneckz/wildless-cms-uni-blocks/pull/269#issuecomment-1228422179

2022-08-26 12:35 UTC, lis42000 commented on src/components/NavigatorTabs/NavigatorTabs.tsx
> +  console.log(navigatorTabs);
Убрал

2022-08-26 12:38 UTC, lis42000 commented on src/components/NavigatorTabs/NavigatorTabs.example.json
> +    { "label": "Tab1", "anchor": "tab1" },
Игорь просил переделать на какие-нибудь тестовые значения без отношения к бизнес логике. Компонент с данными с макета лежит в ContentPage

2022-08-26 12:39 UTC, lis42000 commented on src/components/NavigatorTabs/NavigatorTabItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Вопрос по перемещению блока по странице оставили на дальнейшее обсуждение, просили пока не делать

2022-08-26 12:42 UTC, lis42000 commented on src/components/NavigatorTabs/NavigatorTabs.tsx
> +    ? tabs.map((tab) => (
Поправил

2022-08-27 08:15 UTC, michaelkutuzov commented on src/components/NavigatorTabs/NavigatorTabItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
ОКей) В любом случае надо добавить якоря блокам на ContentPage, чтобы переход можно было посмотреть.

2022-08-29 07:05 UTC, michaelkutuzov commented on src/components/NavigatorTabs/NavigatorTabs.example.json
> +    { "label": "Tab1", "anchor": "tab1" },
ОКай

2022-08-29 07:25 UTC, michaelkutuzov approved these changes

2022-08-29 16:23 UTC, merged