Черновик исправлений #432
redneckz/wildless-cms-uni-blocks pull request #447
Opened 2022-09-19 21:39 UTC by end0rfin

Черновик по задаче [Uni Blocks] Доработка блока Преимущества (BenefitsBlock) #432

2022-09-21 11:01 UTC, Mikage777 commented on src/components/Insurance/Insurance.tsx
> +        {benefit?.description ? renderDescription(benefit?.description) : null}
Не понимаю, откуда появилась надобность тут изменять текущую реализацию бенефитов в компонентах Insurance, и компонентах ниже? 

К тому же, из контента ты явно ожидаешь строки, но потом ты явно указываешь что это другой тип. От этого тип контента не поменяется, тебе в любом случае бы пришла строка, а не объект со свойством name. Почему линтер такое тут позволил не понимаю.

2022-09-21 11:23 UTC, Mikage777 requested changes

2022-09-21 11:23 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +const renderDescriptionBenefit = (descriptions) => {
наверное тут не description**s**, а description. Он один

2022-09-21 11:23 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +const renderListBenefit = (descriptions) => {
нужен тип

2022-09-21 11:23 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +  if (descriptions.items && descriptions.items.length > 0) {
Тут проверку я бы сделал от противного. Если нет того и другого то return null. Кажется читаемой более запись, из-за того что в скобках меньше кода

2022-09-21 11:23 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +export interface DescriptionBenefit {
если убрать ненужное использование подобной реализации списка в других блоках, то по идее, этот интерфейс будет ненужен. Значит свойство можно перенести в DescriptionBenefitDef

2022-09-21 11:39 UTC, Longraf approved these changes

2022-09-21 11:39 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +  return <div className="grid grid-cols-2 gap-8 mt-9">{benefits.map(renderStep)}</div>;
Минимизировать использование grid-cols-... тут совсем без него не обойтись?

2022-09-21 11:39 UTC, Longraf commented on src/components/PictureText/PictureText.tsx
> +        {benefit.description ? renderDescription(benefit.description, version) : null}
лучше benefit?.description

2022-09-21 11:39 UTC, Longraf commented on src/components/PictureText/PictureText.tsx
>              {benefit.label}
59 строка `benefit.label && (`  лучше заменить на тернарник и добавить проверку benefit?.label

2022-09-21 11:43 UTC, Longraf approved these changes

2022-09-21 11:43 UTC, Longraf commented on src/components/BenefitsBlock/BenefitsBlock.fixture.tsx
> +              benefitType: 'list',
Лишний отступ между bullets и items 
И я бы вынес в повторяющиеся части в отдельную переменную. напирмер `items` либо вообще весь description и вывести его в фикстуре через spread

2022-09-21 12:43 UTC, end0rfin commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +export interface DescriptionBenefit {
Раньше description был строкой, сейчас объект {name:string,benefitType:string}. , т.к. добавилась возможность выбора типа описания. Думал насчёт того как реализовать по другому, чтобы остальные блоки не затрагивать, но решение только одно - выделять в отдельный компонент с простой реализацией (просто description:string) для использования в других блоках.

2022-09-21 13:25 UTC, end0rfin commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +export interface DescriptionBenefit {
Отвязал компоненты от интерфейса BenefitsBlock, т.к. он был значительно изменён. Вместо него дополнил эти компоненты отдельным интерфейсом

2022-09-22 13:09 UTC, end0rfin commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +  return <div className="grid grid-cols-2 gap-8 mt-9">{benefits.map(renderStep)}</div>;
Заменил на flex

2022-09-22 13:10 UTC, end0rfin reviewed
Учёл все комментарии и внёс соответствующие правки

2022-09-22 13:25 UTC, Mikage777 requested changes

2022-09-22 13:25 UTC, Mikage777 commented on src/components/ProductBlock/ProductBlock.fixture.mobile.tsx
> +import { ProductBlockBenefit } from './ProductBlockContent';
import type

2022-09-22 13:25 UTC, Mikage777 commented on src/components/ProductBlock/renderBenefit.tsx
> +const renderBenefitDescription = (description, version) => {
типы

2022-09-22 13:25 UTC, Mikage777 commented on src/components/ProductBlock/renderBenefit.tsx
>  function renderBenefitIconBgStyle(version, benefitsVersion) {
типы

2022-09-22 13:25 UTC, Mikage777 commented on src/components/ProductBlock/renderBenefit.tsx
> +  return description.name ? (
Почему-то линтер не поругался у тебя на это. Возможно как раз из-за типов не проставленных. У тебя тут не может быть объекта со свойством name. Ты ждешь строку

2022-09-22 13:30 UTC, Mikage777 commented on src/components/ProductBlock/renderBenefit.tsx
>        <div className="flex gap-0.5 flex-col h-full max-w-[149px]  min-w-[149px]">
пробел лишний

2022-09-22 13:50 UTC, end0rfin reviewed
Внёс исправления по комментариям, которые затёрлись при рефакторинге

2022-09-22 14:27 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +export interface DescriptionBenefit {
Можно избавляться, больше не используется нигде кроме как в DescriptionBenefitDef. Свойство name можно перенести туда

2022-09-22 14:40 UTC, Mikage777 commented on src/components/PictureText/PictureText.tsx
> +const renderDescription = (description, version) => {
типы

2022-09-22 14:41 UTC, Mikage777 commented on src/components/PictureText/PictureText.tsx
> +      {description.name}
не исправлена проблема - пытаешься обратиться к name в объекте. А тут приходит строка. Нужны типы чтобы это увидеть.

2022-09-22 14:46 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlock.tsx
> +      })}
исключительно в целях избавления от лишнего return

2022-09-23 05:26 UTC, Mikage777 commented on src/components/PictureText/PictureText.tsx
> +      {description.name}
Проблема не исправлена..

2022-09-23 05:26 UTC, Mikage777 commented on src/components/PictureText/PictureText.tsx
> +const renderDescription = (description, version) => {
типы не проставлены..

2022-09-23 05:32 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +export type BenefitType = DescriptionBenefitDef | ListBenefitDef | undefined;
Не лучшее решение пихать undefined в типы. Если цель этого undefined сделать пустой option, то воспользуйся EmptyOption, и его нужно вставить в начало

2022-09-23 05:35 UTC, Mikage777 commented on src/components/BenefitsBlock/BenefitsBlockContent.ts
> +  benefitType?: 'description';
лучше вместо description пусть будет text

а то 

```
description: {
benefitType: 'description'
...
}
```

выглядит не очень

2022-09-23 05:50 UTC, end0rfin commented on src/components/PictureText/PictureText.tsx
> +const renderDescription = (description, version) => {
Уже исправлял эти ошибки. Затираются при синхронизации с мэйном.

2022-09-23 05:50 UTC, end0rfin commented on src/components/PictureText/PictureText.tsx
> +      {description.name}
Уже исправлял эти ошибки. Затираются при синхронизации с мэйном.

2022-09-23 08:44 UTC, Mikage777 approved these changes

2022-09-23 08:53 UTC, merged