Catalog block
redneckz/wildless-cms-uni-blocks pull request #475
Opened 2022-09-22 07:50 UTC by andreySimonenko

https://github.com/redneckz/wildless-cms-uni-blocks/issues/373

2022-09-22 07:59 UTC, KolyaBlacK approved these changes

2022-09-22 08:17 UTC, Grimitsu commented on src/components/Catalog/CatalogCard.tsx
> +    style={{ backgroundColor: color.code }}
Если `colors` имеет тип `CatalogProductColors[]`, то сигнатура функции будет
```ts
const renderColorOption = (color: CatalogProductColors, i: number)
```

И если color - юнион с цветом, то в стиле ошибка, поля `code` на нём нет
```
style={{ backgroundColor: color }}
```

2022-09-22 08:18 UTC, Grimitsu commented on src/components/Catalog/CatalogCard.tsx
> +import { BlockVersion } from '../../model/BlockVersion';
import type

2022-09-22 08:18 UTC, Grimitsu commented on src/components/Catalog/CatalogContent.ts
> +  /** Цена */
`/** @title Цена */`

2022-09-22 08:22 UTC, Grimitsu commented on src/components/Catalog/CatalogCard.tsx
> +        {image?.src && <Img className="mb-5" image={image} />}
Кастомный рул не цепляет вложенные поля, может для консистентности переписать `image?.src ? JSX : null`?

2022-09-22 08:23 UTC, Grimitsu commented on src/components/Catalog/CatalogContent.ts
> + * @title Катлог
`Каталог`

2022-09-22 08:24 UTC, Grimitsu commented on src/components/Catalog/CatalogCard.tsx
> +        {price ? <div className="text-title-sm text-left">{price} ₽</div> : null}
Мне кажется стоит добавить сразу NBSPшку перед символом рубля

2022-09-22 08:28 UTC, Grimitsu approved these changes

2022-09-22 08:33 UTC, Grimitsu commented on src/components/Catalog/CatalogContent.ts
> +export type CatalogProductColors = '#000' | '#FFF';
Мне вообще кажется, что стоит подобные перечисления проксировать перечислениями вида
`'black' | 'white'`, и уже исходя из значения, например в мапе, выбирать нужный цвет.
По крайней мере если нет валидации при публикации страницы, это не даст засунуть левый цвет которого нет в перечислении

2022-09-22 10:42 UTC, Mikage777 commented on src/components/Catalog/CatalogContent.ts
> +export type CatalogProductColors = '#000' | '#FFF';
Полагаю здесь лучше использовать нейминг с единственным числом, т.е `CatalogProductColor`.

предположим, `const color: CatalogProductColor = '#000'` будет иметь один цвет. И тогда `const colors: CatalogProductColor[] = ...` много. Что кажется семантически более верно

2022-09-22 11:41 UTC, Longraf approved these changes

2022-09-22 11:41 UTC, Longraf commented on src/components/Catalog/Catalog.fixture.tsx
> +    },
Я бы повторяющиеся элементы поместил в переменную

2022-09-22 11:41 UTC, Longraf commented on src/components/Catalog/Catalog.tsx
> +    </div>
Только что залил рефектор arrowButton замени на 
```
{renderArrows({
    handler: [handlePrevClick, handleNextClick],
    isShown: [showPrevButton, showNextButton],
    btnClass: ['left-8', 'right-8'],
    className: 'top-1/2 mt-6',
})}
```

2022-09-23 09:12 UTC, vladeiko commented on src/components/Catalog/CatalogCard.tsx
> +        {image?.src && <Img className="mb-5" image={image} />}
Поддерживаю. Мы не можем гарантировать что придёт в параметрах.
Например, если на стороне портала кто-то вручную в JSON файле заменить строку на число

2022-09-23 09:22 UTC, vladeiko requested changes

2022-09-23 09:22 UTC, vladeiko commented on src/components/Catalog/Catalog.tsx
> +  ({ context }) =>
```suggestion
  (context) =>
```

Если сделать как выше что изменится? Чем обосновано помещение объекта сюда?
Ещё надо импортировать тип ```ContentPageContext``` и присвоить его.

2022-09-23 09:22 UTC, vladeiko commented on src/components/Catalog/Catalog.tsx
> +          {cards?.length ? cards.map(renderCatalogCard({ context })) : null}
```suggestion
          {cards?.length ? cards.map(renderCatalogCard(context)) : null}
```

2022-09-23 09:22 UTC, vladeiko commented on src/components/Catalog/Catalog.tsx
> +}) => {
Надо написать интерфейс ```RenderNavButtonsProps``` . Обговаривали же таким образом не типизировать

2022-09-23 09:22 UTC, vladeiko commented on src/components/Catalog/Catalog.tsx
> +  const handlePrevClick = () => setActiveCardIndex(activeCardIndex - 1);
Это хендлер. Дальше идут вычисляемые константы. Я считаю, что это всё-таки раздельные логические блоки.

2022-09-27 05:38 UTC, Mikage777 approved these changes

2022-09-27 06:27 UTC, vladeiko approved these changes

2022-09-27 07:55 UTC, merged