Bugfix/steps blocks style maps
redneckz/wildless-cms-uni-blocks pull request #495
Opened 2022-09-26 13:07 UTC by KolyaBlacK

https://github.com/redneckz/temp_wcms/issues/396

2022-09-26 13:14 UTC, vladeiko requested changes

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +    const style = styleMaps(version);
Имя у функции не говорящее. По названию не сразу догадываюсь, что она делает.
Предполагал, что она вернёт map стилей. Так что по моему мнению лучше назвать ```getStyle```.
Такое название говорит, что функция возвращает стили. ```styleMaps``` или  правильнее ```getStyleMaps``` лично мне говорит о том, что эта функция вернёт мапу со стилями (в данном контексте в переменную style).

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +    const style = styleMaps(version);
Если же эта функция возвращает мапу стилей, то лучше назвать ```getStyleMaps```,  а константу ```styleMap```, либо же ```styles```. Хотя, лично я склоняюсь к первому варианту

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +              )(steps.map((step, i) => renderStepIcon(step, i, style)))}
Может быть каррирование лучше будет?

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +              {steps.map((step, i) =>
Может быть каррирование?

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +interface renderStepTitleProps {
```suggestion
interface RenderStepTitleProps {
```

2022-09-26 13:14 UTC, vladeiko commented on src/components/StepsBlock/StepsBlock.tsx
> +const renderStepTitle = (props: renderStepTitleProps) => {
```suggestion
const renderStepTitle = (props: RenderStepTitleProps) => {
```

2022-09-26 14:34 UTC, Mikage777 commented on src/components/StepsBlock/StepsBlock.tsx
> +    const style = styleMaps(version);
getStyleMap - Функция возвращает мапу стилей. 
styleMap - констранта которая содержит конкретную мапу стилей

2022-09-26 17:26 UTC, vladeiko approved these changes

2022-09-27 04:58 UTC, Mikage777 approved these changes

2022-09-27 04:58 UTC, Mikage777 commented on src/components/StepsBlock/StepsBlock.mobile.tsx
> +          <p className={`text-m-md text-center ${styleMap.description} ${title && 'mt-2'}`}>
```suggestion
          <p className={`text-m-md text-center ${styleMap.description} ${title ? 'mt-2' : ''}`}>
```

2022-09-27 04:58 UTC, Mikage777 commented on src/components/StepsBlock/StepsBlock.mobile.tsx
> +    const margin = size === 'normal' ? 'ml-[34px]' : 'ml-[24px]';
```suggestion
    const margin = size === 'normal' ? 'ml-[34px]' : 'ml-6';
```

2022-09-27 08:01 UTC, merged