Office card blocks, build and test (#497)
redneckz/wildless-cms-uni-blocks pull request #498
Opened 2022-09-27 08:26 UTC by AlexsaTasara

Добавляем блок для разводящей страницы офисов.

2022-09-28 07:17 UTC, Longraf commented on src/components/OfficeCard/OfficeCard.tsx
> +        ) : null}
Нет гарантий что эти поля когда будут приходить снаружи точно придут , так что лучше заменить на metro?.name metro?.distance metro?.time и в других местах стоит добавить такие проверки

2022-09-28 20:04 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +        ) : null}
Сделала

2022-10-04 09:34 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +      {currency ? <div className="flex flex-row">{currency.map(renderCurrency)}</div> : null}
тут массив, он может быть пустой, но проверку пройдет в таком случае. Однако мапать будет нечего и код дальше упадет. Поэтому тут нужна проверка на currency.length

2022-10-04 09:34 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +function renderHead({ title, link, location, className }) {
тут нужно типы указать

2022-10-04 09:34 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +          headingType={getTileHeadingType(className)}
почему аргумент функции называется className?

2022-10-04 09:34 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +  curdate?.textColor ? (textcol = curdate.textColor) : null;
обычно следующее слово идет с заглавной букв в  названииях камелкейсом
напримере того, как ты назвала dayOfWeek

2022-10-10 09:27 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  curdate?.textColor ? (textcol = curdate.textColor) : null;
Заменила

2022-10-10 09:27 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +          headingType={getTileHeadingType(className)}
Исправила

2022-10-10 09:27 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +function renderHead({ title, link, location, className }) {
Указала

2022-10-10 09:28 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +      {currency ? <div className="flex flex-row">{currency.map(renderCurrency)}</div> : null}
Добавила

2022-10-12 07:44 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +      {metros ? <div className="flex flex-row">{metros.map(renderMetro)}</div> : null}
тут проверка должна быть на длину массива

2022-10-12 07:44 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +      {contactsInfo ? (
тут тоже

2022-10-12 07:44 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +  curdate?.textColor ? (textCol = curdate.textColor) : null;
тут надо название поправит currentDate
лучше более понятное название тут подобрать, чем textCol

2022-10-12 07:44 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCardContent.ts
> +  dates?: Weekday[];
dayOfWeek лучше

2022-10-12 07:44 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCardContent.ts
> +  currency?: string[];
если это массив, то название должно быть во множественном числе

2022-10-17 08:11 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +      {metros ? <div className="flex flex-row">{metros.map(renderMetro)}</div> : null}
Сделано

2022-10-17 08:12 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +      {contactsInfo ? (
Сделано

2022-10-17 08:12 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  curdate?.textColor ? (textCol = curdate.textColor) : null;
Поправила

2022-10-17 08:13 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCardContent.ts
> +  dates?: Weekday[];
Заменила

2022-10-17 08:14 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCardContent.ts
> +  currency?: string[];
Исправила

2022-10-17 08:14 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  title: string | undefined,
Исправлено

2022-10-24 08:38 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  let textCol = TEXT_COLORS['green'];
Сделана

2022-10-25 08:59 UTC, Irinaristova requested changes

2022-10-25 08:59 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +          <div className="font-medium text-primary-text text-sm m-0">{metro.name}</div>
зачем тут сбрасывать марджины?

2022-10-25 08:59 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +    <div key={String(i)} className="flex flex-col mb-8">
из первых двух div можно создать просто обертку и ее использовать везде, а так ты копипастишь в 3 местах этот код

2022-10-25 08:59 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +  currentDate?.textColor ? (textCol = currentDate.textColor) : null;
почему тут в дефолте null возвращается? должен же красный цвет быть

2022-10-25 08:59 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCardContent.ts
> + * @enumNames [
мы в кр не можем выбирать цвета для текста, это  внутренний функционал компонента, который зависит от входных данных, а не от выбора в редакторе

2022-10-26 12:07 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  currentDate?.textColor ? (textCol = currentDate.textColor) : null;
Исправлено

2022-10-26 12:08 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +          <div className="font-medium text-primary-text text-sm m-0">{metro.name}</div>
Сброс убран

2022-11-01 10:46 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCardContent.ts
> + * @enumNames [
Исправила

2022-11-02 12:02 UTC, Irinaristova requested changes

2022-11-02 12:02 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +    <div key={String(i)} className="flex gap-1 flex-row h-full max-w-[490px] mr-5">
эта обертка дублируется более 3 раз, ее лучше вынести со стилями и переиспользовать

2022-11-02 12:02 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +        <div className={`${TEXT_COLORS['green']} mr-7`}>{openTime}</div>
этих данных может не быть вообще, это опциональный параметр, нужно дописать условие

2022-11-02 12:02 UTC, Irinaristova commented on src/components/OfficeCard/OfficeCard.tsx
> +      </div>
тут может быть 2 блока по макету, добавь, пожалуйста + пример

2022-11-07 08:36 UTC, AlexsaTasara commented on src/components/Blocks.ts
> +import { ContactInformation } from './ContactInformation/ContactInformation';
Исправила

2022-11-07 08:37 UTC, AlexsaTasara commented on src/components/ContactInformation/ContactInformation.tsx
> +  let textcol = TEXT_COLORS['green'];
Изменила

2022-11-07 08:37 UTC, AlexsaTasara commented on src/components/ContactInformation/ContactInformation.tsx
> +      {data.label ? (
Добавила

2022-11-07 08:38 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +        <div className={`${TEXT_COLORS['green']} mr-7`}>{openTime}</div>
Дописала

2022-11-07 08:39 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +      </div>
Добавила

2022-11-07 08:39 UTC, AlexsaTasara commented on src/components/ContactInformation/ContactInformation.tsx
> +              className="w-[48px] h-[48px] min-h-48 min-w-48 bg-main rounded-full box-border p-[12px]"
Добавила

2022-11-07 08:59 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +  const textCol = currentDate.status === 'Без перерыва' ? 'green' : 'red';
Одно условие

2022-11-07 09:07 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +      className={`flex flex-col font-sans text-primary-text py-10 bg-white divide-solid divide-black divide-y pr-8 pl-8 pt-8 pb-8 divide ${className}`}
Они были лишние и сейчас убраны.

2022-11-08 11:07 UTC, AlexsaTasara commented on src/components/ContactInformation/ContactInformation.tsx
> +function renderData(data: ContactData, i: number) {
Переназвала

2022-11-08 11:08 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +            {location?.adress}
Добавила

2022-11-08 11:08 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +          <div className=" mb-1 flex gap-1 flex-row h-full font-medium text-xl text-base">
Убрала

2022-11-08 11:09 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +          <div className=" mb-2 flex gap-10 flex-row h-full font-medium text-2xl justify-start text-primary-text">
Убрала

2022-11-08 11:09 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.tsx
> +            <div className="">{title}</div>
Убрала

2022-11-08 11:09 UTC, AlexsaTasara commented on src/components/OfficeCard/OfficeCard.fixture.tsx
> +export const DATES: DayOfWeek[] = [
Добавила

2022-11-24 13:17 UTC, Mikage777 commented
Необходимые материалы и код будут переиспользованы в задачах https://github.com/redneckz/wildless-cms-uni-blocks/issues/694 и https://github.com/redneckz/wildless-cms-uni-blocks/issues/691
Данный МР закрываю в связи со сложностью его поддержки по актуальным требованиям.

2022-11-24 13:17 UTC, closed without merging