update examples
redneckz/wildless-cms-uni-blocks pull request #507
Opened 2022-09-27 17:12 UTC by Irinaristova

2022-09-27 17:55 UTC, Mikage777 commented on src/components/Accordion/Accordion.example.json
> +          "style": "col-span-12"
Очень расстраиваюсь когда вижу что код пишут лишь бы просто написать.. Достаточно просто посмотреть в интерфейсы, чтобы понять что ожидается здесь.

`style?: string[];`

Буквально недавно проговаривали что цикл проверки..

2022-09-27 17:56 UTC, Mikage777 requested changes
Переделать.

2022-09-28 06:31 UTC, redneckz approved these changes

2022-09-28 11:37 UTC, Mikage777 approved these changes

2022-09-28 11:37 UTC, merged