Bugfix 332 fix stepsblock
redneckz/wildless-cms-uni-blocks pull request #530
Opened 2022-09-30 06:59 UTC by Irinaristova

Ссылка на баг - https://github.com/redneckz/temp_wcms/issues/332

2022-09-30 07:05 UTC, Grimitsu approved these changes

2022-09-30 07:15 UTC, lis42000 commented on .public.package.json
> +  "version": "0.3.81",
Текущая версия 0.3.83, нужно вмержить свежий мейн

2022-09-30 12:47 UTC, michaelkutuzov approved these changes

2022-09-30 12:47 UTC, michaelkutuzov commented on src/components/StepsBlock/StepsBlock.tsx
> +  (styleMap: StyleType, isMainButton: boolean, version) => (step: Step, i: number) => {
Тип version

2022-09-30 12:47 UTC, michaelkutuzov commented on src/components/StepsBlock/StepsBlock.tsx
> +        className="flex flex-col items-center justify-between text-center relative w-[276px] whitespace-pre-line overflow-hidden"
Чет вот константы эти как-то грустно смотрятся, тип 276px

2022-10-03 07:07 UTC, Longraf approved these changes

2022-10-03 07:07 UTC, Longraf commented on src/components/StepsBlock/StepsBlock.tsx
>      const styleMap = getStyleMap(version);
Мне не понятно зачем лишняя функция для стилей `getStyleMap` можно же напрямую сделать импорт 
 `STEPS_BLOCK_STYLE_MAPS[version]`

2022-10-03 07:07 UTC, Longraf commented on src/components/StepsBlock/StepsBlock.tsx
>              <div className="flex items-center px-[88px]">
В одном случае `max-w-[47rem]` в другом `px-[88px]` Вроде везде в таких кейсах используем px ,

2022-10-06 05:51 UTC, Mikage777 requested changes

2022-10-06 05:51 UTC, Mikage777 commented on install_nvm.sh
> +#!/usr/bin/env bash
этот файл тут зачем?

2022-10-06 05:51 UTC, Mikage777 commented on src/components/ExchangeRateTile/renderButton.tsx
> +import { ButtonProps } from '../../ui-kit/Button/ButtonProps';
type

2022-10-06 05:51 UTC, Mikage777 commented on src/components/StepsBlock/StepsBlock.tsx
> +    const router = useRouter();
https://ru.reactjs.org/docs/hooks-rules.html

2022-10-07 10:21 UTC, Mikage777 approved these changes

2022-10-07 11:24 UTC, merged