Feature/api safe deposit rental
redneckz/wildless-cms-uni-blocks pull request #660
Opened 2022-10-18 08:47 UTC by KolyaBlacK

https://github.com/redneckz/temp_wcms/issues/507

2022-10-18 09:59 UTC, lis42000 commented on src/components/SafeDepositRental/SafeBoxCases.tsx
> +import { SafeBoxCase, SafeBoxCaseVolume } from './SafeDepositRentalContent';
import type

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/RegionsAndBranches.tsx
> +          {regions.length ? (
тут regions?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/RegionsAndBranches.tsx
> +          {branches.length ? (
branches?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/RenderRadioButtons.tsx
> +        className="mb-2"
при уменьшении размера окна кругляш сплющивает

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/RentalPeriod.tsx
> +const ITEMS = ['От 1 дня', 'До 365 дней'];
мб контсанты луше выносить отдельно?

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeBoxCases.tsx
> +          {caseVolumes.length ? (
caseVolumes?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeBoxCases.tsx
> +          {safeBoxCases.length ? (
safeBoxCases?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRental.tsx
> +        {regions.length ? <SafeDepositRentalInner regions={regions} /> : null}
regins?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRental.tsx
>          <p className="text-s-light text-secondary-text">
мб этот текст лучше вынести в константу?

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRental.tsx
>            Аренда СЯ, в случае проведения процедуры купли-продажи, с использованием наличных денег
это постоянный текст? мб не стоит его так хардкодить?

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRentalForm.tsx
> +        {regions.length ? (
regions?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRentalForm.tsx
> +        {caseVolumes.length && safeBoxCases.length ? (
caseVolumes?.length && safeBoxCases?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/SafeDepositRentalInner.tsx
> +  if (branches.length && branches[0]?.branchCode) {
branches?.length

2022-10-18 11:52 UTC, Irinaristova commented on src/components/SafeDepositRental/WrapperSelect.tsx
> +          {data.map((_, i) => (
data?.length ? data.map() ...

2022-10-18 13:30 UTC, KolyaBlacK commented on src/components/SafeDepositRental/RentalPeriod.tsx
> +const ITEMS = ['От 1 дня', 'До 365 дней'];
@Irinaristova зачем? используется в одном месте

2022-10-18 13:37 UTC, KolyaBlacK commented on src/components/SafeDepositRental/WrapperSelect.tsx
> +          {data.map((_, i) => (
@Irinaristova  зачем? data обязательное поле

2022-10-19 09:14 UTC, vladeiko requested changes

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/RegionsAndBranches.tsx
> +  handleSelectedBranch: (value: string) => void;
```suggestion
  onBranchSelect: (value: string) => void;
```

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/RenderRadioButtons.tsx
> +  const [selected, setSelected] = useState('option1');
```suggestion
  const [selectedOption, setSelectedOption] = useState('option1');
```

Иначе воспринимается как булевое. Не уверен, что это лучшее значение по умолчанию

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/RenderRadioButtons.tsx
> +  const onChange = (_: React.ChangeEvent<HTMLInputElement>) => setSelected(_.target.value);
Добавить отступ сверху

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/SafeDepositRentalInner.tsx
> +  }, [selectedBranch]);
Выглядит очень перегруженно

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/SafeDepositRentalInner.tsx
> +          setDays={setDays}
Слишком много пропсов принимает.
И я вижу, что они идут из текщуего компонента в дочерний и больше никуда. Так может объявить их в дочернем?

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/RegionsAndBranches.tsx
> +  handleSelectedRegion: (value: string) => void;
```suggestion
  onRegionSelect: (value: string) => void;
```

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/RentalPeriod.tsx
> +const ITEMS = ['От 1 дня', 'До 365 дней'];
Я бы поместил все константы до интерфейса

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/SafeBoxCases.tsx
> +  setSelectedBoxSize: (value: string) => void;
Многовато пропсов.
Каждый из компонентов получает отсюда по три пропса.
Почему на уровень выше (в родительском компоненте) не разместить просто две рендер-функции, котоыре примет по три пропса?

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/SafeBoxCases.tsx
> +  setSelectedBoxSize: (value: string) => void;
Думаю, так правильнее

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/SafeDepositRentalForm.tsx
> +  setDays: (value: number) => void;
Слишком много пропсов. Надо декомпозировать

2022-10-19 09:14 UTC, vladeiko commented on src/components/SafeDepositRental/useGetRegions.ts
> +async function fetchRegions(): Promise<Region[]> {
Вроде как была добавлена функция, для фетча JSON файлов

2022-10-21 06:21 UTC, redneckz approved these changes

2022-10-21 07:13 UTC, vladeiko approved these changes

2022-10-21 07:19 UTC, Mikage777 approved these changes

2022-10-21 07:19 UTC, merged