add error component
redneckz/wildless-cms-uni-blocks pull request #663
Opened 2022-10-18 11:23 UTC by Irinaristova

Ссылка на ишью - https://github.com/redneckz/wildless-cms-uni-blocks/issues/602

2022-10-19 07:15 UTC, andreySimonenko commented on src/components/Error/Error.fixture.tsx
> +          numberValue: 404,
правильнее будет назвать code или  errorCode

2022-10-19 07:17 UTC, andreySimonenko commented on src/components/Error/Error.tsx
> +            className="min-w-[239px] py-4 px-9"
размер кнопки зависит от контента и отступов, зачем тут `min-w-[239px]`?

2022-10-20 07:25 UTC, Irinaristova commented on src/components/Error/Error.fixture.tsx
> +          numberValue: 404,
тут не всегда будет код на картинки, есть примеры, где просто каринка - технический перерыв

2022-10-20 09:49 UTC, Mikage777 requested changes

2022-10-20 09:49 UTC, Mikage777 commented on src/components/ErrorComponent/ErrorComponentContent.ts
> +}
не правильный интерфейс. Как я уже говорил, нужно использовать механизм который используется в аккардионе. Мы должны получить на выходе `anyOf`, который в форме будет интерпретироваться как дропдаун. Также нарушен конвеншен по использованию префикса `*Content`.

```suggestion
/**
 * @title Изображение
 */
export type ErrorImageDef =  {
    /** @default Image */
    errorContentType: 'Image';
    image?: Picture;
};

/**
 * @title Код ошибки
 */
export type ErrorCodeDef =  {
    /** @default Code */
    errorContentType: 'Code';
    code?: number;
};

export type ErrorContentDef = EmptyOption | ErrorImageDef | ErrorCodeDef;
```

Также требуется в КР в ui:schema скрыть поле errorContentType

2022-10-20 09:49 UTC, Mikage777 commented on src/components/ErrorComponent/ErrorComponentContent.ts
> +export interface ErrorComponentContent {
```suggestion
export interface ErrorBlockContent {
```

2022-10-20 09:49 UTC, Mikage777 commented on src/components/ErrorComponent/ErrorComponent.fixture.tsx
> +  alt: 'Ощибка',
```suggestion
  alt: 'Ошибка',
```

2022-10-20 09:49 UTC, Mikage777 commented on src/components/ErrorComponent/ErrorComponent.tsx
> +              className="mb-7 h-[294px] w-[460px] min-w-[460px] min-h-[294px]"
я думаю не самая лучшая идея здесь указывать фиксированные значения для картинки. А если редактор хочет позже увидеть картинку наибольшего тут размера, или наименьшего? Придется выпускать новую версию юниблоков ради этого. Для выбора размеров изображений у нас есть инструменты в КР. Мы можем задать необходимые размеры по умолчанию аннотацией `@default { ... }` для поля `image`

2022-10-21 06:42 UTC, Mikage777 commented on src/components/ErrorBlock/ErrorBlockContent.ts
> +   */
что то тут поплыло помоему. Зачем нам тут дефолтный объект свойств от картинки для `errorContentType`?

2022-10-21 06:44 UTC, Mikage777 commented on src/components/ErrorBlock/ErrorBlock.tsx
> +    return <Img className="mb-7" image={error.image} width="460" height="294" />;
Убери пожалуйста здесь размеры. Я уже писал что они не нужны тут. Размеры картинок должны устанавливаться редактором

2022-10-21 06:52 UTC, Mikage777 commented on src/components/ErrorBlock/ErrorBlock.tsx
> +import type { ErrorBlockContent, ErrorContentDef, ErrorImageDef } from './ErrorBlockContent';
Гитхаб подсказывает что эти типы не используются

2022-10-21 08:48 UTC, Mikage777 approved these changes

2022-10-21 08:52 UTC, merged