Вкладки. Исправил ошибку при создании новой вкладки, поправил стиль кол-ва элементов
redneckz/wildless-cms-uni-blocks pull request #705
Opened 2022-10-24 13:02 UTC by end0rfin

Задача:
e2e.Пример основного сайта. Кабинет редактора. Вкладки. Ошибка в блоке при добавлении нвой вкладки
https://github.com/redneckz/temp_wcms/issues/536

2022-10-24 13:11 UTC, Mikage777 requested changes
нужен скрипт миграции. 

`tabs` -> `tabBlocks`

2022-10-24 14:30 UTC, Mikage777 commented on bin/migration-scripts/0.4.5.js
> +  });
Давай это в новый файл. Этот уже неактуален. 
Новую версию возьми из актуального `.public.package.json`, предврительно подняв там на 1 ее

2022-10-24 14:30 UTC, Mikage777 commented
Также потребуется изменение ui:schema в КР

2022-10-24 15:09 UTC, end0rfin commented on bin/migration-scripts/0.4.5.js
> +  });
Обновил версию и добавил соответствующий скрипт миграции

2022-10-24 19:43 UTC, end0rfin commented
Ещё раз прошёлся по проекту на предмет повторного/лишнего использования типа Tab и свойства tabs.
Обнаружил что элемент Tabs из ui-kit нигде в проекте не задействован, но в нём используется такой же тип и свойство tabs: Tab. Удалил лишний компонент ui-kit/Tabs. Именование типа и свойства в компоненте components/Tabs оставил прежними. 
Скрипты миграции также удалил.

2022-10-25 07:37 UTC, Longraf approved these changes

2022-10-25 07:49 UTC, Mikage777 approved these changes

2022-10-25 09:14 UTC, merged