fix issues-578
redneckz/wildless-cms-uni-blocks pull request #732
Opened 2022-10-31 08:31 UTC by Longraf

https://github.com/redneckz/temp_wcms/issues/578

2022-10-31 13:26 UTC, Mikage777 commented on src/components/PictureText/PictureTextContent.ts
> +import { BlockVersion } from '../../model/BlockVersion';
type

2022-10-31 15:42 UTC, Irinaristova requested changes

2022-11-01 05:15 UTC, Longraf commented on src/components/PictureText/PictureTextContent.ts
> +import { BlockVersion } from '../../model/BlockVersion';
Done

2022-11-01 05:23 UTC, Longraf commented on src/components/__snapshots__/Blocks.spec.tsx.snap
> +  class="relative font-sans py-[50px] px-[100px] bg-white text-primary-text "
Т.к. на странице портала эти атомы не работали. Сейчас в портале найти не могу, а локально проверил вроде работает. Вернул атомы py-12 px-28

2022-11-01 06:12 UTC, Irinaristova approved these changes

2022-11-01 07:06 UTC, merged