DRAFT fix input number
redneckz/wildless-cms-uni-blocks pull request #748
Opened 2022-11-02 13:16 UTC by Longraf

https://github.com/redneckz/temp_wcms/issues/584

2022-11-07 13:29 UTC, Irinaristova approved these changes

2022-11-07 13:52 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      let val = String(e.target.value.replace(',', '.').replace(/[^.\d]/g, ''));
Может NumberFormat? А утилит для форматирования у нас нет разве (на основе NumberFormat)

2022-11-07 13:53 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      val = val.startsWith('.') ? val.replace('.', '0.') : val;
сложно такое воспринимать
нудна декомпозиция на несколько мелких функций с понятными названиями

2022-11-07 13:53 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +function checkMinMax(val, minValue, maxValue) {
clamp же есть для этого в утилитах

2022-11-07 13:53 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +function onlyOneDot(val) {
подозрительная фугкция)

2022-11-07 13:56 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> -            type="number"
почему ушел тип?
может lang атрибут может повлиять на форматирование числе в type=number?

2022-11-07 13:57 UTC, redneckz requested changes
С локализацией надо аккуратнее. Скорее всего можно обойтись встроенным API
Кастомное решение я бы как крайний вариант рассматривал

2022-11-07 14:06 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +function checkMinMax(val, minValue, maxValue) {
В случае с clamp в input невозможно проставить точку

2022-11-07 14:08 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> -            type="number"
Тип ушёл из-за бага в mozila при type="number" можно вводить буквы

2022-11-08 09:11 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      let val = String(e.target.value.replace(',', '.').replace(/[^.\d]/g, ''));
Утилит нет, т.к. раньше либо не было задачи с вбиванием копеек, Либо не было защиты от ввода нескольких точек

2022-11-08 09:12 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +function onlyOneDot(val) {
Не позволяет ввести второй разделитель в виде точки, ранее это было сделать возможно

2022-11-08 09:31 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      val = val.startsWith('.') ? val.replace('.', '0.') : val;
вынес в отдельные функции
Done

2022-11-08 09:47 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      let val = String(e.target.value.replace(',', '.').replace(/[^.\d]/g, ''));
NumberFormat может выдавать в input "не число" а та же стирает  точку и её невозможно ввести

2022-11-09 09:57 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
>        if (!onChange) {
Типизация события
`e: { target: { value: string } | null }`

2022-11-09 09:59 UTC, redneckz commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      let val = e.target.value as string;
просто композиция функций
`const = onlyOneDot(setZeroStart(replaceCommaToDot(e.target.value)));`

2022-11-09 10:03 UTC, redneckz approved these changes

2022-11-09 10:46 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
>        if (!onChange) {
Done

2022-11-09 10:53 UTC, Longraf commented on src/ui-kit/CurrencyInput/CurrencyInput.tsx
> +      let val = e.target.value as string;
Если передавать в onChange clampVal без тернарника, то при преобразовании стирается точка и её невозможно ввести в input

2022-11-09 12:07 UTC, merged