Add pull requests doc
redneckz/wildless-cms-uni-blocks pull request #759
Opened 2022-11-06 18:54 UTC by vladeiko

Задача:
1. Написать документацию по созданию и принятию pull requests
2. Написать документацию по написанию commits

2022-11-07 08:10 UTC, redneckz commented on PULL_REQUESTS.md
> +Файл содержит информацию о правилах создания pull requests и оформления commits
`# Правила процесса Code Review`

2022-11-07 08:13 UTC, redneckz commented on PULL_REQUESTS.md
> +# Pull реквесты
Можно обойтись без этого заголовка и вступительного слова. Чем короче и содержательнее заголовки, тем лучше

2022-11-07 08:14 UTC, redneckz commented on PULL_REQUESTS.md
> +## **Автор**
Автор PR/MR

2022-11-07 08:22 UTC, redneckz commented on PULL_REQUESTS.md
> +2.  Заполнить описание
есть какие то пожеланию по формату описания?

2022-11-07 08:38 UTC, redneckz commented on PULL_REQUESTS.md
> +3.  Сообщить остальным разработчикам ссылку на pull request
Ссылку на PR/MR в general канал с коротким описанием того что сделано

...
Здесь речь про наш конкретный процесс, поэтому наша специфика нужна

2022-11-07 08:39 UTC, redneckz commented on PULL_REQUESTS.md
> +4.  Ждать подтверждения или комментариев
Сколько именно ждать? У нас есть проблема с зависшими MR - это тоже надо регулировать данным процессом

2022-11-07 08:41 UTC, redneckz commented on PULL_REQUESTS.md
> +4.  Ждать подтверждения или комментариев
Что делать с зависшими MR?

2022-11-07 08:56 UTC, redneckz commented on PULL_REQUESTS.md
> +2.  Заполнить описание
Здесь можно сослаться на секцию ниже. Либо подставить её как подпункты

2022-11-07 14:56 UTC, redneckz approved these changes

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +2.  Коммит всегда пишется в Present Simple
Imperative будет точнее сказать

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +В данном разделе описаны удачные и не очень примеры коммитов
эти вводные слова особо погоды не делают, так как контекст достаточно простой.

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +### Как не надо
```
## Не очень
```

(стараюсь избегать резких оттенков в заголовках)

```
1. нет необходимости
1. каждый пункт нумеровать самостоятельно
1. markdown сам расставит номера
```

1. нет необходимости
1. каждый пункт нумеровать самостоятельно
1. markdown сам расставит номера

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +Ниже представлен список "неудачных" коммитов:
Тоже необязательное вступительное слово (из заголовков понятно)

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +Неплохой пример:
Я прочитал как "плохой пример" и удивился)

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +Неплохой пример:
Можно смело назвать хорошим примером

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +### Как надо
```
### Хорошо
```

2022-11-07 14:56 UTC, redneckz commented on devDocs/COMMITS.md
> +### Как надо
Чтобы избежать явного призыва в заголовке

2022-11-07 14:56 UTC, redneckz commented on devDocs/PULL_REQUESTS.md
> +git rebase origin main // Применяет изменения
```
$ git rebase origin/main
```

2022-11-07 14:56 UTC, redneckz commented on devDocs/PULL_REQUESTS.md
> +Отличий от команды `git pull origin main` минимальные. Решение конфликтов может происходить в 2-3 итерации. Зато даёт выигрыш в чистой истории коммитов.
Если MR атомарен, то коммит там один, и отличий от git merge никаких не должно быть
git rebase из одного этапа

2022-11-07 14:56 UTC, redneckz commented on devDocs/REQUEST_AUTHOR.md
> +# Правила и инструкции для автора PR/MR
можно без "и инструкции"

2022-11-07 14:56 UTC, redneckz commented on devDocs/REQUEST_AUTHOR.md
> +Естественно, Вы **не всегда можете быть согласны** с комментариями, которые Вам оставили. В таком случае Вам необходимо сначала посмотреть на **Главное правило**, а затем следовать следующему алгорит
Не уверен, что для этого случая нужна погшаговая инструкция. Высушил бы до одного предложения

2022-11-07 14:56 UTC, redneckz commented on devDocs/REQUEST_AUTHOR.md
> +4.  В зависимости от результата дискуссии либо не вносить изменения и отметить комментарий как **resolved** (последний комментарий в ветке должен быть от того, кто эти изменения предложил и содержать
На мой взгляд, лучше не учить ребят методам ведения переговоров. Главное здесь - это фиксация договорённости (которая может быть достигнута в discord) в нитке комментария, чтобы было понятно что именно будет фикситься

2022-11-07 14:57 UTC, redneckz commented on devDocs/REQUEST_AUTHOR.md
> +1.  Ознакомиться с содержимым комментария. Если что-то непонятно, можно обратиться к его автору для уточнения, оставив комментарий (нет гарантий, что Вам ответят быстро), либо написать в личные сообщ
Желательно такие пункты высушивать. Слишком многословно. Только суть отражать, а эмоции делать нейтральными максимально

2022-11-07 14:59 UTC, redneckz commented on devDocs/REQUEST_REVIEWER.md
> +2.  Если вы видите, что можно внести исправление, то оставляете комментарий, в котором предлагаете внести изменение. Если изменение небольшое, то можно использовать hotkey `Ctrl + G`, предварительно
пункты из нескольких предложений - лучше высушивать. или разбивать на подпункты

2022-11-08 06:32 UTC, Guzlik123 approved these changes

2022-11-08 06:35 UTC, lis42000 commented on devDocs/REQUEST_REVIEWER.md
> +Если реквест оформлен как `Darft`, не рекомендуется ставить ему `Approve` до перевода в `Ready for review`
Draft?

2022-11-08 06:36 UTC, lis42000 approved these changes

2022-11-08 06:39 UTC, Longraf approved these changes

2022-11-08 07:32 UTC, tatinacher approved these changes

2022-11-08 07:35 UTC, andreySimonenko approved these changes

2022-11-08 07:38 UTC, Grimitsu approved these changes

2022-11-08 07:38 UTC, SergeyPilipenko approved these changes

2022-11-08 08:05 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +git rebase origin/main // Применяет изменения
Использование именно rebase я бы прям как-то ОСОБО выделил

2022-11-08 08:05 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +Если оставлен комментарий, требующий внесения измений, то нет необходимости создавать отдельный коммит, вносящий исправления (например: `Fix after review`), достаточно отредактировать код и вполнить
изменений

2022-11-08 08:05 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +git commit --amend --no-edit // Вносит текущие изменения в последний коммит на ветке
Добавляет изменения к последнему существующему коммиту, не изменяя название коммита

2022-11-08 08:05 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +Перед влитем реквеста необходимо убедиться, что в ветке ровно **один** коммит и все изменения и синхронизации проводились по инструкции выше.
влитием

2022-11-08 08:05 UTC, michaelkutuzov commented on devDocs/REQUEST_AUTHOR.md
> +1.  Опубликовать ссылку на реквест в `general` канал в нашем `Discord` сервере
протегав @CMS/uni blocks developers. Если вас нет на нашем Дискорд-сервере, обратитесь к коллегам, вам помогут

2022-11-08 08:09 UTC, michaelkutuzov commented on devDocs/CODE_REVIEW.md
> +# Правила процесса Code Review
Плюс, я бы добавил описание того, как именно тестируются юни-блоки перед отправкой на реквест

2022-11-08 08:26 UTC, end0rfin approved these changes

2022-11-08 08:26 UTC, end0rfin commented on devDocs/COMMITS.md
> +Wrap PageEditorPanel elemnts into ErrorBoundary
... elemEnts ...

2022-11-08 08:26 UTC, end0rfin commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Поскольку все русскоговорящие работают над проектом для оформления MR/PR целесообразнее использовать родной язык.

2022-11-08 08:26 UTC, end0rfin commented on devDocs/COMMITS.md
> +1.  Текст коммита должен отражать суть проделанной работы
Добавить пункт:
- Для последующих коммитов, повозможности, использовать параметр "--amend" для "склеивания" коммитов в один.

Этот пункт указан в оформлении MR/PR, но думаю лучше обозначить его здесь тоже.

2022-11-08 08:26 UTC, end0rfin commented on devDocs/REQUEST_REVIEWER.md
> +1.  Если автор реквеста **согласен** с предложенными изменениям, он их внесёт и отметит комментарий как `Resolved`
Немного не согласуется с "Главным правилом".
Может уточнить главное правило в части "если полностью согласен с комментарием и вносимые изменения не нарушают общее состояние коммита, то вносить изменения и резолвить".

2022-11-08 08:49 UTC, vladeiko commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Немного противоречит утверждению в репозитории CMS: https://github.com/redneckz/temp_wcms/blob/master/DOCUMENTATION_AGREEMENT.md

Тут сказано, что мы не можем быть уверены разработчик какой национальности будет иметь дело с решением, решение может быть вынесено в open source. Стоит обсудить этот момент

2022-11-08 08:51 UTC, vladeiko commented on devDocs/COMMITS.md
> +1.  Текст коммита должен отражать суть проделанной работы
В этом файле документируется правило оформления коммита (его имя).
В другом документе мы утверждаем, что какие-то дополнительные изменения в коммит вносятся через --amend. И это по сути не коммиты, а расширение уже существующего (фиксы, дописывание логики)

2022-11-14 11:26 UTC, Mikage777 approved these changes

2022-11-15 06:17 UTC, Irinaristova requested changes

2022-11-15 06:17 UTC, Irinaristova commented on devDocs/COMMITS.md
> +
добавила бы необходимость указания номера таски в названии коммита

2022-11-15 06:17 UTC, Irinaristova commented on devDocs/COMMITS.md
> +1.  Add
а также что именно это за коммит: bug, feature, hotfix

2022-11-15 06:17 UTC, Irinaristova commented on devDocs/REQUEST_AUTHOR.md
> +1.  Ждать подтверждения или комментариев
можно указать минимальное количество аппрувов ревьюеров

2022-11-15 06:17 UTC, Irinaristova commented on devDocs/REQUEST_AUTHOR.md
> +Никогда не отмечать комментарии как `Resolved` в одностороннем порядке (без согласования с **автором** и/или кем-то ещё).
можно использовать комментс конвеншен, чтобы понимать насколько существенный коммент

2022-11-15 08:59 UTC, vladeiko commented on devDocs/CODE_REVIEW.md
> +# Правила процесса Code Review
Не относится к процессу Code Review. Это к Devdoc скорее всего

2022-11-15 09:17 UTC, end0rfin commented on devDocs/REQUEST_REVIEWER.md
> +1.  Если автор реквеста **согласен** с предложенными изменениям, он их внесёт и отметит комментарий как `Resolved`
Этот пункт оставить как есть.
Предлагаю отредактировать Главное правило так:
"Отмечать комментарии как `Resolved` при согласовании с автором комментария (или его заместителем), либо в одностороннем порядке при условии полного согласия с комментарием и внесением соответствующих корректировок в код ."

2022-11-15 09:20 UTC, end0rfin commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Указанная дока имеет отношение к документированию кода (важные комментарии в методам в коде, оформление справки, типизации и т.д.), т.е. непосредственно к оформлению самого кода. Я же предлагаю использовать родной язык в качестве оформления MR/PR.

2022-11-15 09:33 UTC, vladeiko commented on devDocs/REQUEST_REVIEWER.md
> +1.  Если автор реквеста **согласен** с предложенными изменениям, он их внесёт и отметит комментарий как `Resolved`
Решили отказаться от главного правила и добавить его содержимое в чеклист

2022-11-15 09:48 UTC, michaelkutuzov commented on devDocs/COMMITS.md
> +1.  Add
Это должен быть префикс у ветки, а не у коммита

2022-11-15 09:50 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Разумно создавать ветки прямо в интерфейсе борды. 
![image](https://user-images.githubusercontent.com/20220032/201887567-e6f648ae-55c7-4a13-b48e-7f9f6183fa83.png)

2022-11-15 09:51 UTC, michaelkutuzov commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Тогда имя реквеста будет привязано к задаче, и из задачи будет сразу видно, в какой ветке она делается

2022-11-15 10:04 UTC, vladeiko commented on devDocs/COMMITS.md
> +
На общее обсуждение

2022-11-15 10:05 UTC, vladeiko commented on devDocs/COMMITS.md
> +1.  Add
На общее обсуждение

2022-11-15 10:09 UTC, vladeiko commented on devDocs/REQUEST_AUTHOR.md
> +Никогда не отмечать комментарии как `Resolved` в одностороннем порядке (без согласования с **автором** и/или кем-то ещё).
На общее обсуждение

2022-11-16 15:56 UTC, vladeiko commented on devDocs/PULL_REQUESTS.md
> +К именованию MR/PR применимы правила именования [коммитов](COMMITS.md)
Решено вливать как есть. Данное предложение предлагается оформить в виде отдельного PR

2022-11-16 15:57 UTC, vladeiko commented on devDocs/COMMITS.md
> +
Решено вливать как есть. Данное предложение предлагается оформить в виде отдельного PR

2022-11-16 15:57 UTC, vladeiko commented on devDocs/COMMITS.md
> +1.  Add
Решено вливать как есть. Данное предложение предлагается оформить в виде отдельного PR

2022-11-16 15:57 UTC, vladeiko commented on devDocs/REQUEST_AUTHOR.md
> +1.  Ждать подтверждения или комментариев
Решено вливать как есть. Данное предложение предлагается оформить в виде отдельного PR

2022-11-16 15:59 UTC, vladeiko commented on devDocs/REQUEST_AUTHOR.md
> +Никогда не отмечать комментарии как `Resolved` в одностороннем порядке (без согласования с **автором** и/или кем-то ещё).
Решено вливать как есть. Данное предложение предлагается оформить в виде отдельного PR

2022-11-17 08:05 UTC, michaelkutuzov approved these changes

2022-11-17 11:12 UTC, Irinaristova approved these changes

2022-11-18 16:54 UTC, merged