Add investment gallery
redneckz/wildless-cms-uni-blocks pull request #855
Opened 2022-11-23 06:06 UTC by Irinaristova

ссылка - https://github.com/redneckz/wildless-cms-uni-blocks/issues/813

2022-11-23 06:50 UTC, vladeiko requested changes

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +    const cardClassName = version === 'secondary' ? 'border-white/50' : 'border-main-stroke';
'cardClassName' is assigned a value but never used

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +        className={className}
```suggestion
        key={String(i)}
        context={context}
        version={version}
        className={className}
        {...card}
```

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +}) => {
Типизацию в интерфейс

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +  const showPrevButton = isUseSlider && activeCardIndex > 0;
Отделить вычисляемые значения от хендлеров.
Желательно сначала вычисляемые значения записать, потом через отступ хендлеры

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +        handler: [handlePrevClick, handleNextClick],
Странно, что массивом передаётся

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +        isShown: [showPrevButton, showNextButton],
Странно, что массивом передаётся

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +const getItemListFontSize = (colValue) => (colValue === '1' ? 'text-h6' : 'text-l');
Нет типизации

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +  ({ className = '', columnsCount, context, description, image, cardList, title, version }) => {
'version' is defined but never used

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +                ))}
Если тут не используются переменные кроме `item`, лучше вынести в рендер-функцию

2022-11-23 06:50 UTC, vladeiko commented on src/components/InvestmentGallery/InvestmentGalleryContent.ts
> +import type { ListContent } from '../../ui-kit/List/ListContent';
'ListContent' is defined but never used

2022-11-23 08:08 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +        isShown: [showPrevButton, showNextButton],
Это реалзиация `renderArrows` из `src/ui-kit/Button/renderArrows.tsx`, это типизировано как кортежи на 2 элемента, так как для навигации нужно 2 кнопки-стрелки.
2 хендлера, 2 флага isShown, 2 стринги с классами под кнопки

2022-11-23 12:50 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryContent.ts
> +import type { ListContent } from '../../ui-kit/List/ListContent';
поправила

2022-11-23 12:51 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +const getItemListFontSize = (colValue) => (colValue === '1' ? 'text-h6' : 'text-l');
поправила

2022-11-23 12:52 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +        className={className}
поправила

2022-11-23 14:19 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +    const cardClassName = version === 'secondary' ? 'border-white/50' : 'border-main-stroke';
поправила

2022-11-23 14:21 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +  ({ className = '', columnsCount, context, description, image, cardList, title, version }) => {
поправила

2022-11-23 14:24 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +}) => {
поправила

2022-11-24 08:57 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      ],
cardList: можно вынести в константу

2022-11-24 08:57 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +    return (
от return можно избавиться и запись сократиться

2022-11-24 08:57 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +import { Heading } from '../../ui-kit/Heading/Heading';
У нас уже есть компонент Headline который объединяет Heading и Description проверь пожалуйста можно ли его тут использовать.

2022-11-24 08:57 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +            {cardList?.length ? (
Для лучшей читабельности я предлагаю вынести в функцию renderCardList

2022-11-24 12:20 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +                ))}
поправила

2022-11-24 12:21 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      ],
ок

2022-11-24 12:21 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +    return (
ок

2022-11-24 12:21 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +            {cardList?.length ? (
уже был этот коммент, поправила

2022-11-24 12:21 UTC, Irinaristova commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +import { Heading } from '../../ui-kit/Heading/Heading';
проверю

2022-11-24 12:36 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +import { Heading } from '../../ui-kit/Heading/Heading';
Согласен, по вёрстке headline сюда не подхоидт

2022-11-24 12:38 UTC, Longraf approved these changes

2022-11-24 14:14 UTC, vladeiko approved these changes

2022-11-24 14:26 UTC, Grimitsu approved these changes

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      ],
Это заменить бы на `cardList: cardListExample` как ниже, значения вроде все те же

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      additionalDescription: 'Краткосрочная',
это тоже можно свернуть в cardsCommonProps и заспредить здесь `{...cardsCommonProps}` и в карточках ниже

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      additionalDescription: 'Краткосрочная',
Как и выше `{...cardsCommonProps}`

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGallery.fixture.tsx
> +      additionalDescription: 'Краткосрочная',
И тут тоже `{...cardsCommonProps}`

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +                <div className="text-m-light text-secondary-text"> {additionalDescription} </div>
Пробелы вокруг `additionalDescription` нужны?

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +      {item?.parametr ? (
`parameter`

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGalleryCard.tsx
> +      {item?.parametrDesccription ? (
`parameterDescription`

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGalleryContent.ts
> +  parametr?: string;
`parameter`

2022-11-24 14:26 UTC, Grimitsu commented on src/components/InvestmentGallery/InvestmentGalleryContent.ts
> +  parametrDesccription?: string;
`parameterDescription`

2022-12-07 14:03 UTC, Longraf commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +  ({ context, version, className }) =>
`className = ''`

2022-12-07 14:08 UTC, tatinacher approved these changes

2022-12-08 13:15 UTC, tatinacher approved these changes

2022-12-08 13:15 UTC, tatinacher commented on src/components/ProductGallery/ProductGallery.tsx
>  import { ContentPageContext } from '../ContentPage/ContentPageContext';
type

2022-12-08 13:15 UTC, tatinacher commented on src/components/InvestmentGallery/InvestmentGallery.tsx
> +  (context: ContentPageContext, className: string, version?: BlockVersion) =>
className лучше сделать optional

2022-12-08 13:18 UTC, Grimitsu commented on src/components/ProductGallery/ProductGallery.tsx
>  import { ContentPageContext } from '../ContentPage/ContentPageContext';
Это не тип, константа импортиурется, хотя возможно и не совсем корректно, что у нас мапы в части файлов в моделях лежат

2022-12-08 13:18 UTC, tatinacher commented on src/components/ProductGallery/ProductGallery.tsx
>  import { ContentPageContext } from '../ContentPage/ContentPageContext';
не то выделилось, type на ContentPageContext

2022-12-08 14:24 UTC, merged