Refactor gallery,implement cardsgallery
redneckz/wildless-cms-uni-blocks pull request #890
Opened 2022-11-30 08:28 UTC by Irinaristova

Ссылка на таску - https://github.com/redneckz/wildless-cms-uni-blocks/issues/858

2022-11-30 08:31 UTC, Longraf commented
Нужно объявить GalleryNew в Blocks.ts

2022-12-02 10:32 UTC, lis42000 commented on src/components/GalleryNew/GalleryBlocksItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
'JSX' is defined but never used
Он точно нужен в этой функциии? Может переписать на компонент?

2022-12-02 10:32 UTC, lis42000 commented on src/components/GalleryNew/GalleryBlocksTypesProps.ts
> +import { ContentPageContext } from '../ContentPage/ContentPageContext';
import type

2022-12-02 10:32 UTC, lis42000 commented on src/components/GalleryNew/GalleryNew.tsx
> +    className,
Лучше тут задать className = '', судя по пропсам - может прийти undefined

2022-12-02 10:32 UTC, lis42000 commented on src/components/GalleryNew/GalleryNew.ui.json
> +{}
Точно нужен этот файл? Будет расширяться?

2022-12-02 10:35 UTC, Irinaristova commented on src/components/GalleryNew/GalleryNew.tsx
> +    className,
поправлю

2022-12-02 10:35 UTC, Irinaristova commented on src/components/GalleryNew/GalleryBlocksTypesProps.ts
> +import { ContentPageContext } from '../ContentPage/ContentPageContext';
поправлю

2022-12-02 10:35 UTC, Irinaristova commented on src/components/GalleryNew/GalleryBlocksItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
поправлю

2022-12-02 10:35 UTC, Irinaristova commented on src/components/GalleryNew/GalleryNew.ui.json
> +{}
этот файл нужен для кр

2022-12-02 11:04 UTC, Longraf commented on src/components/GalleryNew/GalleryBlocksItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Мне по названию совсем не понятно за что отвечает GalleryBlocksItem.
Если я правильно понял то это скорее GalleryNewInner или GalleryNewContainer
Возможно новый компонент вообще стоит называть Carousel а не GalleryNew что бы не путаться?
Тогда Carousel будет приватным компонентом который мы помещаем в ui-kit т.к. он не может существовать без наполнения.

Как я себе вижу структуру нового компонента на примере компонента Ивана
ui-kit/Carousel - приватный
component/CarouselBankHistory/
<CarouselBankHistory>
   <Carousel>
      <CarouselBankHistoryItem>
   </Carousel/>
<CarouselBankHistory/>

Так же предлагаю для того что бы схожие по функционалу компоненту в IDE были рядом в названии первым словом ставить Carousel

2022-12-02 11:04 UTC, Longraf commented on src/components/GalleryNew/GalleryNew.tsx
> +import { renderGalleryBlock } from './GalleryBlocksItem';
Почем у в импорте рендер функции оказался компонент?

2022-12-02 11:26 UTC, tatinacher commented on src/components/GalleryNew/GalleryBlocksItem.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Плюсую, кажется, что название Gallery все же к галерее относится, для карусели лучше название Carousel или Slider

2022-12-02 11:28 UTC, Longraf commented on src/ui-kit/GalleryCard/GalleryCard.tsx
> +            ) : null}
У нас же уже есть компонент Headline для случаев когда есть title и description

2022-12-02 11:33 UTC, Longraf commented on src/ui-kit/GalleryCard/GalleryCard.tsx
> +import { JSX } from '@redneckz/uni-jsx';
Если правильно понимаю GalleryCard это карточка из "старого" компонента Галерея и GalleryCard больше нигде не планируется использовать кроме как в "старой" Галереи, соответственно не уверен в правильности его выноса в ui-kit

2022-12-07 12:55 UTC, lis42000 requested changes

2022-12-07 12:55 UTC, lis42000 commented on src/components/Carousel/Carousel.tsx
> +    version,
'version' is defined but never used, он не понадобился?

2022-12-07 12:55 UTC, lis42000 commented on src/components/Carousel/CarouselContent.ts
> +  galleryBlocks?: any[];
лучше использовать VNode

2022-12-07 12:55 UTC, lis42000 commented on src/components/Carousel/CarouselContent.ts
> +  version?: BlockVersion;
если version не пригодился, можно убрать?

2022-12-07 12:55 UTC, lis42000 commented on src/components/Carousel/renderNavButtons.tsx
> +  galleryBlocks?: any[];
лучше использовать VNode

2022-12-07 12:55 UTC, lis42000 commented on src/components/CarouselCard/CarouselCard.tsx
> +    const descriptionStyles = button ? 'mb-3' : '';
'descriptionStyles' is assigned a value but never used

2022-12-07 12:55 UTC, lis42000 commented on src/components/CarouselCard/CarouselCard.tsx
> +  version?: BlockVersion;
нужен ли version? ниже вроде не используется, + он есть в типе CarouselCardContent

2022-12-08 06:50 UTC, vladeiko requested changes

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/Carousel.tsx
> +import { CarouselItemsList } from './CarouselItemsList';
Импорты не отсортированы

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/Carousel.tsx
> +        : `translateX(-${activeCardIndex * cardShift}px)`;
```suggestion
    const [activeCardIndex, setActiveCardIndex] = useState(0);
    
    const GalleryBlurClasses = isBlur ? 'absolute top-0 bottom-0 w-[84px]' : '';
    
    const CardFullViewStyles =
      cardFullViewCount === 1
        ? `translateX(-${activeCardIndex * 100}%)`
        : `translateX(-${activeCardIndex * cardShift}px)`;
```

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/Carousel.tsx
> +          <CarouselItemsList>{galleryBlocks}</CarouselItemsList>
А действительно ли надо было было вот этот вот <ul> со сбросом стилей выносить в отдельный компонент?
```suggestion
          <ul className="list-none m-0 p-0">{galleryBlocks}</ul>
```

Компонент CarouselItemsList только тут и используется. А если всё-таки хочется вынести, то надо выносить в ui-kit и заменять на этот wrapper везде, где используется такой же <ul>

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/CarouselItemsList.tsx
> +export const CarouselItemsList = JSX(({ children }) => (
А точно надо выносить в отдельный компонент? Используется только в одном месте. Выше расписал

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/renderNavButtons.tsx
> +  setActiveCardIndex: (index: number) => void;
Мне кажется, что здесь что-то не так. Во-первых, вряд ли проп должен зваться `setActiveCardIndex`. Мне кажется, что проблемы с декомпозицией имеют место быть. Как минимум этот проп должен начинаться с `on`

2022-12-08 06:50 UTC, vladeiko commented on src/components/Carousel/renderNavButtons.tsx
> +  };
Приличный объём вычислений. Полагаю, что это скорее компонент, чем рендер-функция

2022-12-08 06:50 UTC, vladeiko commented on src/components/CarouselCard/CarouselCard.tsx
> +import { Headline } from '../Headline/Headline';
По-моему, импорты не отсортированы

2022-12-12 06:39 UTC, Longraf commented on mobile/src 12/model/GalleryVersion.ts
> +export type GalleryVersion = 'normal' | 'mini';
Не понял что за папка src 12 ?

2022-12-12 06:39 UTC, Longraf commented on src/components/Carousel/CarouselContent.ts
> +import { VNode } from '../../model/VNode';
type

2022-12-12 06:39 UTC, Longraf commented on src/components/Carousel/CarouselNavButtons.tsx
> +import { VNode } from '../../model/VNode';
type

2022-12-12 06:41 UTC, Longraf approved these changes

2022-12-13 13:13 UTC, tatinacher approved these changes

2022-12-14 13:02 UTC, vladeiko requested changes

2022-12-14 13:02 UTC, vladeiko commented on src/components/CarouselCard/constants.ts
> +};
Только что проверил. Обе константы используются ТОЛЬКО в CarouselCard.tsx

2022-12-14 13:02 UTC, vladeiko commented on src/components/Carousel/CarouselContainer.tsx
> +    const widthClasses = isBankCarousel ? '[&>*]:max-w-[1/3]' : 'w-auto';
Может лучше прям там и вставить это выражение? Мне не очень нравится имя переменной

2022-12-15 10:02 UTC, vladeiko requested changes

2022-12-15 10:02 UTC, vladeiko commented on src/components/Carousel/Carousel.fixture.tsx
> +  'carusel with mini cards': (
```suggestion
  'carousel with mini cards': (
```

2022-12-15 10:02 UTC, vladeiko commented on src/components/Carousel/CarouselNavButtons.tsx
> +  ({ isScrollAvailable, inc, deck, canInc, canDec, activeItem }) => {
```suggestion
  ({ isScrollAvailable, inc, dec, canInc, canDec, activeItem }) => {
```

2022-12-15 11:11 UTC, vladeiko approved these changes

2022-12-15 11:11 UTC, vladeiko commented on src/components/Carousel/Carousel.tsx
> +    const carouselArrowProps = useCarouselControl({
```suggestion
    const [activeItem, controls] = useCarouselControl({
```

2022-12-15 11:11 UTC, vladeiko commented on src/components/Carousel/Carousel.tsx
> +
```suggestion
```

2022-12-15 11:11 UTC, vladeiko commented on src/hooks/useCarousel.ts
> +interface CarouselProps {
```suggestion
}

interface CarouselProps {
```

2022-12-15 11:11 UTC, vladeiko commented on src/hooks/useCarousel.ts
> +export interface Controls {
```suggestion
export type CarouselControlProps = [number, Controls];

export interface Controls {
```

2022-12-15 11:17 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  const inc = (_: number) => setActiveItem((_ + 1) % itemsCount);
useCallback никто не отменял

2022-12-15 11:37 UTC, lis42000 approved these changes

2022-12-15 11:59 UTC, redneckz approved these changes

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +export const useCarouselControl = ({
хуки не обязаны располагаться в папке hooks (только, если общие какие то совсем, типа useBoolean)

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  const inc = useCallback((_: number) => setActiveItem((_ + 1) % itemsCount), []);
```ts
const inc = useCallback(
  setActiveItem((_) => isCyclic
    ? (_ + 1) % itemsCount)
    : Math.min(_ + 1, itemsCount - 1)
  ),
  []);

const dec = useCallback(
  setActiveItem((_) => isCyclic
    ? (itemsCount + _ - 1) % itemsCount
    : Math.max(_ - 1, 0)
  ),
  []);
```

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  const cyclicComplexity = isCyclic && isScrollAvailable;
isCyclicAndScrollAvailable

2022-12-15 11:59 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +      isCyclic: isCyclic,
`isCyclic,`

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  const [activeItem, setActiveItem] = useState(0);
`activeIndex, setActiveIndex`

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  visibleItemCount: number;
```suggestion
  visibleItemCount?: number;
```

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  isCyclic: boolean;
```suggestion
  isCyclic?: boolean;
```

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  visibleItemCount,
```suggestion
  visibleItemCount = itemsCount,
```

2022-12-15 11:59 UTC, redneckz commented on src/components/Carousel/CarouselNavButtons.tsx
> +    const handleNextClick = () => inc(activeItem);
они уходят

2022-12-15 11:59 UTC, redneckz commented on src/components/Carousel/CarouselNavButtons.tsx
> +          handler: [handlePrevClick, handleNextClick],
```suggestion
          handler: [dec, inc],
```

2022-12-15 11:59 UTC, redneckz commented on src/components/Carousel/CarouselNavButtons.tsx
> +  ({ isScrollAvailable, activeItem, controls }) => {
```suggestion
  ({ isScrollAvailable, activeItem, controls: { inc, dec, canDec, canInc }  }) => (
    ...
  )
```

2022-12-15 11:59 UTC, redneckz commented on src/components/Carousel/CarouselNavButtons.tsx
> +export const CarouselNavButtons = JSX<CarouselNavButtonsProps>(
а нужен ли этот компонент вообще?

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  inc: (idx: number) => void;
```suggestion
  inc: () => void;
```

2022-12-15 11:59 UTC, redneckz commented on src/hooks/useCarousel.ts
> +  dec: (idx: number) => void;
```suggestion
  dec: () => void;
```

2022-12-15 12:05 UTC, redneckz commented on src/components/Carousel/CarouselContent.ts
> +  cards?: VNode[];
эта декларация не требуется

2022-12-15 12:05 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +    cards = [],
```suggestion
    chilrden,
```

2022-12-15 12:05 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +          {cards}
{chilrden}

2022-12-15 12:06 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +export const Carousel = JSX<CarouselProps>(
```suggestion
export const Carousel: JSXBlock<CarouselProps> = JSX<CarouselProps>(
```

2022-12-15 12:07 UTC, redneckz commented on src/components/Carousel/CarouselContainer.tsx
> +CarouselContainer.childrenTypes = ['CarouselCard'];
это уходит в Carousel

2022-12-15 12:07 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +    ...rest
здесь будет `block`

2022-12-15 12:09 UTC, redneckz commented on src/components/Carousel/Carousel.tsx
> +    const isScrollAvailable = cards?.length > cardFullViewCount;
```suggestion
    const { blocks: childBlocks } = block || {};
    const isScrollAvailable = childBlocks?.length > cardFullViewCount;
```

2022-12-15 12:10 UTC, redneckz approved these changes

2022-12-15 14:13 UTC, Mikage777 commented on src/components/Carousel/Carousel.tsx
> +    slots,
гит подсказывает, что ни page, ни slots не используются

2022-12-15 14:15 UTC, Mikage777 commented on src/components/Carousel/CarouselContainer.tsx
> +        className={`w-auto flex flex-1 duration-1000`}
```suggestion
        className="w-auto flex flex-1 duration-1000"
```

2022-12-15 14:17 UTC, Mikage777 commented on src/components/Carousel/CarouselContainer.tsx
> +export interface ContainerProps extends CarouselContainerProps, UniBlockProps {}
`UniBlockProps` в данном случае будет misusage, тк этот контейнер является по сути приватным компонентом, а не самостоятельным блоком

2022-12-15 14:19 UTC, Mikage777 commented on src/components/Carousel/CarouselContent.ts
> +  isCyclic?: boolean;
тут не хватает аннотации, для редактора будут не понятны эти поля. Если они не нужны для отображения в КР, то их нужно скрыть аннотацией `@hidden`

2022-12-15 14:28 UTC, Mikage777 approved these changes

2022-12-15 14:59 UTC, merged